### ISSUE TITLE
异常如下：java.lang.UnsatisfiedLinkError: No implementation found for boolean 

### ISSUE THREAD

**Issue by Andoridswordsman** [apache/incubator-weex#1565]
![Uploading WechatIMG17959.jpeg…]()
weex版本：Android：0.18.7-beta-1
项目ndk配置如下：
ndk {
            abiFilters "armeabi", "x86"
        }
这些机型运行报错，不知道是什么问题，错误信息如下：
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.taobao.weex.bridge.WXBridge.nativeNotifyLayout(java.lang.String) (tried Java_com_taobao_weex_bridge_WXBridge_nativeNotifyLayout and Java_com_taobao_weex_bridge_WXBridge_nativeNotifyLayout__Ljava_lang_String_2)
	at com.taobao.weex.bridge.WXBridge.nativeNotifyLayout(Native Method)
	at com.taobao.weex.bridge.WXBridge.notifyLayout(WXBridge.java:534)
	at com.taobao.weex.bridge.WXBridgeManager.notifyLayout(WXBridgeManager.java:2546)
	at com.taobao.weex.WXSDKInstance.OnVSync(WXSDKInstance.java:1959)
	at com.taobao.weex.RenderContainer.OnVSync(RenderContainer.java:110)
	at com.taobao.weex.WeexFrameRateControl$1.doFrame(WeexFrameRateControl.java:51)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5258)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by Andoridswordsman** [comment]
有遇到过这问题的吗？一个月了还没人解答。

**Comment by zshshr** [comment]
Please give us  a Github address  of android studio project  that can debug this issue .
And I will handle this issue as soon as possible.

**Comment by zshshr** [comment]
Please give us a Github address of an Android Studio project that we can reappear this issue ，
and we will handle this issue as soon as possible @Andoridswordsman

**Comment by Andoridswordsman** [comment]
this issue occurred online, i can't reappear it

**Comment by Andoridswordsman** [comment]
MI PAD 2 is happens often

**Comment by Andoridswordsman** [comment]
> Please give us a Github address of an Android Studio project that we can reappear this issue ，
> and we will handle this issue as soon as possible @Andoridswordsman
this issue occurred online, i can't reappear it

**Comment by Andoridswordsman** [comment]
> Please give us a Github address of an Android Studio project that we can reappear this issue ，
> and we will handle this issue as soon as possible @Andoridswordsman
this issue occurred online, i can't reappear it。 MI PAD 2 is happens often

**Comment by Andoridswordsman** [comment]
> Please give us a Github address of an Android Studio project that we can reappear this issue ，
> and we will handle this issue as soon as possible @Andoridswordsman

**Comment by Andoridswordsman** [comment]
@zshshr @Hanks10100 this issue occurred online, i can't reappear it，MI PAD 2 is happens often

**Comment by Andoridswordsman** [comment]
> > Hi x86 has been supported in the latest code. Please try it again
> 
> @Darin726 0.19.0.5?

which center? I can't compile

Error:Could not find weex_sdk.aar (com.taobao.android:weex_sdk:0.19.0.5).
Searched in the following locations:
 http://maven.aliyun.com/nexus/content/groups/public/com/taobao/android/weex_sdk/0.19.0.5/weex_sdk-0.19.0.5.aar

**Comment by Andoridswordsman** [comment]
> Hi x86 has been supported in the latest code. Please try it again

compile "com.taobao.android:weex_sdk:0.19.0.5@release.aar"   it't ok?

**Comment by YorkShen** [comment]
#1694 

Sorry the delay, you can use `compile 'com.taobao.android:weex_sdk:0.19.0.7'`. I have checked, it worked well
