### ISSUE TITLE
`$ weex create helloworld` 报一系列警告（错误）

### ISSUE THREAD

**Issue by forwardNow** [apache/incubator-weex#1604]
## Description

使用 `$ weex create helloworld` 报一系列警告（错误），不知道会不会影响后续的使用。

## Environment

```shell
$ weex -v
   v1.3.11
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```

## Broken Example

```shell
wuqinfeis-iMac:work forwardNow$ which weex
/usr/local/bin/weex
wuqinfeis-iMac:work forwardNow$ cd /Users/forwardNow/develop/work/study/Mobile/weex/projects
wuqinfeis-iMac:projects forwardNow$ weex create helloworld
This command need to install weexpack. Installing...
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: In file included from ../fsevents.cc:85:
'Call' is deprecated../src/methods.cc :[-Wdeprecated-declarations]14:
12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);  handler->Call(3, argv);

           ^
           ^
../../nan/nan.h../../nan/nan.h::16171617::33::  notenote: : 'Call''Call' has been explicitly  has been explicitly marked markeddeprecated  deprecatedhere here

  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h../../nan/nan.h::9898::4040::  notenote: : expandedexpanded  fromfrom  macromacro  'NAN_DEPRECATED''NAN_DEPRECATED'

# define NAN_DEPRECATED __attribute__((deprecated))# define NAN_DEPRECATED __attribute__((deprecated))

                                       ^                                       ^

1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/fsevents
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);
           ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  handler->Call(3, argv);
           ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
1 warning generated.
sed: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/forwardNow/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/fsevents
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
? Project name helloworld
? Project description A weex project
? Author forwardNow <wuqinfei_csdn@163.com>
? Select weex web render latest
? Babel compiler (https://babeljs.io/docs/plugins/#stage-x-experimental-presets) stage-0
? Use vue-router to manage your view router? (not recommended) Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Airbnb
? Set up unit tests No
? Should we run `npm install` for you after the project has been created? (recommended) npm
12:36:28 : Generated helloworld


# Installing project dependencies ...
# ========================

npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!

> fsevents@1.2.4 install /Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld/node_modules/fsevents
> node install

[fsevents] Success: "/Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.

added 1454 packages from 765 contributors in 22.628s


Running eslint --fix to comply with chosen preset rules...
# ========================


> helloworld@1.0.0 lint /Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld
> eslint --ext .js,.vue src  --fix


Success! Created helloworld at /Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld

Inside that directory, you can run several commands:


  npm start
  Starts the development server for you to preview your weex page on browser
  You can also scan the QR code using weex playground to preview weex page on native

  npm run dev
  Open the code compilation task in watch mode

  npm run ios
  (Mac only, requires Xcode)
  Starts the development server and loads your app in an iOS simulator

  npm run android
  (Requires Android build tools)
  Starts the development server and loads your app on a connected Android device or emulator

  npm run pack:ios
  (Mac only, requires Xcode)
  Packaging ios project into ipa package

  npm run pack:android
  (Requires Android build tools)
  Packaging android project into apk package

  npm run pack:web
  Packaging html5 project into `web/build` folder

  npm run test
  Starts the test runner

To get started:

  cd helloworld
  npm start

Enjoy your hacking time!
wuqinfeis-iMac:projects forwardNow$ ce helloworld/
-bash: ce: command not found
wuqinfeis-iMac:projects forwardNow$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/forwardNow/.npm/_logs/2018-10-01T04_37_12_401Z-debug.log
wuqinfeis-iMac:projects forwardNow$ ls
helloworld
wuqinfeis-iMac:projects forwardNow$ cd helloworld/
wuqinfeis-iMac:helloworld forwardNow$ ls
README.md		ios.config.json		package.json		src
android.config.json	node_modules		platforms		web
configs			package-lock.json	plugins			webpack.config.js
wuqinfeis-iMac:helloworld forwardNow$ npm start

> helloworld@1.0.0 start /Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld
> npm run serve


> helloworld@1.0.0 serve /Users/forwardNow/develop/work/study/Mobile/weex/projects/helloworld
> webpack-dev-server --env.NODE_ENV=development --progress

 95% emitting

 DONE  Compiled successfully in 6020ms                                                                       12:37:42 PM

 I  Your application is running here: http://192.168.1.116:8081.


 WAIT  Compiling...                                                                                          12:37:43 PM

 95% emitting

 DONE  Compiled successfully in 44ms                                                                         12:37:43 PM

 I  Your application is running here: http://192.168.1.116:8081.

^C
wuqinfeis-iMac:helloworld forwardNow$ weexpack
-bash: weexpack: command not found
wuqinfeis-iMac:helloworld forwardNow$ cat /Users/forwardNow/.npm/_logs/2018-10-01T04_37_12_401Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.9.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /Users/forwardNow/develop/work/study/Mobile/weex/projects
6 verbose Darwin 17.7.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 verbose node v10.9.0
9 verbose npm  v6.4.1
10 error missing script: start
11 verbose exit [ 1, true ]
```

## Steps to Reproduce

安装完 weex ，第一次创建项目。

**Comment by erha19** [comment]
@forwardNow you can see the document here http://weex.apache.org/cn/guide/index.html.

@Hanks10100 And this issue is no longer active, it can be temporarily closed.
