### ISSUE TITLE
请问weex-loader如何支持coffeescript

### ISSUE THREAD

**Issue by noman798** [apache/incubator-weex#1655]
weex run web 一切正常

weex run android报错如下

```
    ERROR in ./node_modules/weex-vue-loader/lib/script-loader.js!./node_modules/babel-loader/lib!./node_modules/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue
    Module build failed: SyntaxError: Unexpected token (11:10)

       9 | export default {
      10 |   name: 'App',
    > 11 |   data : ->
         |           ^
      12 |     {
      13 |       logo: 'https://gw.alicdn.com/tfs/TB1yopEdgoQMeJjy1XaXXcSsFXa-640-302.png'
      14 |     }

     @ ./src/index.vue 9:18-170
     @ ./src/entry.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! phone.life@1.0.0 build: `webpack --env.NODE_ENV=common`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the phone.life@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/z/.npm/_logs/2018-10-23T07_58_28_963Z-debug.log
15:58:28 : Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
15:58:28 : Error: Error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! phone.life@1.0.0 build: `webpack --env.NODE_ENV=common`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the phone.life@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/z/.npm/_logs/2018-10-23T07_58_28_963Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
```

![image](https://user-images.githubusercontent.com/12876555/47345155-a5f13e00-d6dc-11e8-9ea6-a513c8372c48.png)

已经配置了configs/vue-loader.conf.js 的 lang（见截图）

**Comment by noman798** [comment]
测试了一下，pug和scss不做任何配置都可以用，coffee怎么配置都没法和安卓的weex-loader一起用，但是可以和web一起用
