### ISSUE TITLE
合入0.19的正式版，Didn't find class "com.taobao.windmill.bridge.WMLBridge"

### ISSUE THREAD

**Issue by simonwu-os** [apache/incubator-weex#1702]
Didn't find class "com.taobao.windmill.bridge.WMLBridge".
这个会导致不能正常运行的问题吗？目前合入新版本，原有的代码不能运行.

11-05 10:28:56.700 5965-6027/com.wcheer.demo W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bridge.WMLBridge" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.wcheer.demo-2/base.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.wcheer.demo-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.wcheer.demo-2/lib/arm, /vendor/lib, /system/lib]]
11-05 10:28:56.700 5965-6027/com.wcheer.demo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-05 10:28:56.700 5965-6027/com.wcheer.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

**Comment by simonwu-os** [comment]
恩，后面我们自己解决了。 好像有个地方关于是WXSDKEngine.m 里面initSDKEnvironment初始化的时候。默认是显示空白。没有加载任何页面。 后面增加了失败机制，如果失败用原来的就可以加载页面了。
    NSString *fileName = @"weex-main-jsfm";
    [WXSDKManager sharedInstance].multiContext = YES;
    if ([[NSUserDefaults standardUserDefaults] objectForKey:@"createInstanceUsingMutliContext"]) {
        BOOL createInstanceUsingMutliContext = [[[NSUserDefaults standardUserDefaults] objectForKey:@"createInstanceUsingMutliContext"] boolValue];
        if (!createInstanceUsingMutliContext) {
            fileName = @"native-bundle-main";
            [WXSDKManager sharedInstance].multiContext = NO;
        }
    }
    ///wcheer.com added by simon 2018.11.10
    else{
        fileName = @"native-bundle-main";
        [WXSDKManager sharedInstance].multiContext = NO;
    }
    ///wcheer.com end of added
