### ISSUE TITLE
加载本地js文件导致OOM

### ISSUE THREAD

**Issue by zhouxuemeng1988** [apache/incubator-weex#1732]
java.lang.OutOfMemoryError
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:82)
	at java.lang.StringBuilder.<init>(StringBuilder.java:67)
	at com.taobao.weex.utils.WXFileUtils.readStreamToString(WXFileUtils.java:86)
	at com.taobao.weex.utils.WXFileUtils.loadFileOrAsset(WXFileUtils.java:52)
	at com.gochinatv.ad.WXPageBaseActivity$1.run(WXPageBaseActivity.java:270)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5039)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:843)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:659)
	at dalvik.system.NativeStart.main(Native Method)

## Environment
FINGERPRINT=HiSTBAndroidV5/Hi3798MV100/Hi3798MV100:4.4.2/Sbox8G40C/817120000087:eng/test-keys

weex sdk version ：   'com.taobao.android:weex_sdk:0.18.0'

加载本地js文件，偶现bug，本地js文件最多的为332KB
<img width="796" alt="2018-11-09 17 54 36" src="https://user-images.githubusercontent.com/26111953/48255843-d1985600-e448-11e8-97aa-586eebaa79e3.png">

**Comment by Mrhejunjie** [comment]
Hello, I also reproduce the problem, do you have any good solution？
