### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by zhouxuemeng1988** [apache/incubator-weex#1773]
java.lang.OutOfMemoryError
	at java.lang.String.<init>(String.java:354)
	at java.lang.String.<init>(String.java:228)
	at com.taobao.weex.http.WXStreamModule.readAsString(WXStreamModule.java:239)
	at com.taobao.weex.http.WXStreamModule$2.onResponse(WXStreamModule.java:177)
	at com.taobao.weex.http.WXStreamModule$StreamHttpListener.onHttpFinish(WXStreamModule.java:352)
	at com.taobao.weex.adapter.DefaultWXHttpAdapter$1.run(DefaultWXHttpAdapter.java:84)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

 oom crash bug
 implementation 'com.taobao.android:weex_sdk:0.18.0'
deveice info :
TIME=1470298853000
FINGERPRINT=HiSTBAndroidV5/Hi3798MV100/Hi3798MV100:4.4.2/Sbox8G40C/817120000052:eng/test-keys
HARDWARE=bigfish
UNKNOWN=unknown
RADIO=HiSTBAndroidV600R001C00SPC064
BOARD=bigfish
versionCode=79
PRODUCT=Hi3798MV100
versionName=3.1.7
DISPLAY=Sbox8G40C test-keys
USER=banlei
HOST=ubuntu
DEVICE=Hi3798MV100
TAGS=test-keys
MODEL=Sbox8G40C
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=true
devicesId=115b4a60f821592
ID=Sbox8G40C
SERIAL=005501FF0001181001F808A5C869C99C
MANUFACTURER=Hisilicon
BRAND=HiSTBAndroidV5
TYPE=eng

**Comment by zshshr** [comment]
Give me more information like environment, or reproducible demo that can run on the http://dotwe.org  site？

**Comment by zhouxuemeng1988** [comment]
@zshshr 偶然出现的bug，暂时无法提供必现路径。
