### ISSUE TITLE
weex Android中 list 渲染异常 导致APP崩溃

### ISSUE THREAD

**Issue by yubinbin** [apache/incubator-weex#1956]
- [ ] Review the documentation: https://weex.apache.org/index.html
  - [ ] Search for existing issues: https://github.com/apache/incubator-weex/issues
  - [ ] Use the latest Weex release: https://github.com/apache/incubator-weex/releases

# Describe the bug
weex中更改列表数据时，在已有数据前面添加数据时，渲染时程序异常崩溃。

#概率：
20%，非必现，但是有概率，10次会出现1-2次。

## Environment
* Device: 红米Note4
* OS: [Android ]
* Version [7.0]
* weex 版本 0.19.0.7

E/CrashReport: java.util.ConcurrentModificationException
        at android.support.v4.util.SimpleArrayMap.removeAt(SimpleArrayMap.java:566)
        at android.support.v4.util.SimpleArrayMap.remove(SimpleArrayMap.java:501)
        at com.taobao.weex.ui.RenderContextImpl.unregisterComponent(RenderContextImpl.java:78)
        at com.taobao.weex.ui.WXRenderManager.unregisterComponent(WXRenderManager.java:152)
        at com.taobao.weex.ui.action.GraphicActionRemoveElement.clearRegistryForComponent(GraphicActionRemoveElement.java:51)
        at com.taobao.weex.ui.action.GraphicActionRemoveElement.executeAction(GraphicActionRemoveElement.java:45)
        at com.taobao.weex.ui.action.BasicGraphicAction.run(BasicGraphicAction.java:58)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by YorkShen** [comment]
Already fix, we will publish a new version later

**Comment by flyminiboy** [comment]
遇到了同样的问题，新版本大概需要多久呢？
