### ISSUE TITLE
[Android]input组件不触发@input方法

### ISSUE THREAD

**Issue by wangchunlei000** [apache/incubator-weex#2116]
你好，weex-sdk版本为0.17.0时，在使用input组件时@input方法无法正常回调，输入内容后删除输入框中的内容，再输入其他字符，就无法回调到@input方法中，代码如下：
`<input
      type="tel"
      maxlength="13"
      class="recharge_phone--input"
      placeholder="请输入手机号"
      placeholder-color="#bbbbbb"
      :value="phoneFormat"
      @input="onInput"
      @focus="onFocus"
      @blur="onBlur"
      ref="phoneInput"
    >
`
在AndroidStudio中抓取的log如下：
`
02-12 16:07:23.626 1574-1574/com.dwd.rider D/CLog: java.lang.NumberFormatException: For input string: "0.422"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.taobao.weex.utils.WXUtils.parseUnitOrPercent(WXUtils.java:392)
        at com.taobao.weex.utils.WXResourceUtils$1.map(WXResourceUtils.java:50)
        at com.taobao.weex.utils.WXResourceUtils$1.map(WXResourceUtils.java:47)
        at com.taobao.weex.utils.SingleFunctionParser$1.map(SingleFunctionParser.java:52)
        at com.taobao.weex.utils.FunctionParser.function(FunctionParser.java:78)
        at com.taobao.weex.utils.FunctionParser.definition(FunctionParser.java:63)
        at com.taobao.weex.utils.FunctionParser.parse(FunctionParser.java:57)
        at com.taobao.weex.utils.SingleFunctionParser.parse(SingleFunctionParser.java:77)
        at com.taobao.weex.utils.WXResourceUtils$ColorConvertHandler$3.handle(WXResourceUtils.java:400)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:246)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:232)
        at com.taobao.weex.ui.component.WXComponent.setBackgroundColor(WXComponent.java:1333)
        at com.taobao.weex.ui.component.WXComponent.setProperty(WXComponent.java:756)
        at com.taobao.weex.ui.component.WXComponent.updateProperties(WXComponent.java:698)
        at com.taobao.weex.ui.component.WXComponent.updateStyle(WXComponent.java:425)
        at com.taobao.weex.ui.component.WXComponent.bindData(WXComponent.java:415)
        at com.taobao.weex.ui.component.WXVContainer.bindData(WXVContainer.java:164)
        at com.taobao.weex.dom.action.AddElementAction.executeRender(AddElementAction.java:115)
        at com.taobao.weex.dom.RenderActionTask.execute(RenderActionTask.java:50)
        at com.taobao.weex.ui.WXRenderManager$1.run(WXRenderManager.java:104)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
`
设备信息如下：
OS：Android & iOS
device：xiaomi8
system：Android 9.0
weex-sdk:0.17.0

还请及时反馈下，这个问题对开发影响较大。

**Comment by YorkShen** [comment]
1. Update to the latest version of Weex.
2. Give a [demo](http://dotwe.org/vue)

I am looking forward to your reply.

Thanks

**Comment by YorkShen** [comment]
As there is no updated, I will just close the issue.

Feel free to reopen it with a demo and test it in the latest version of Weex.
