### ISSUE TITLE
[Android] [noClassDefFounfError IWxDebugAdapter] Unexpected behavior when breakPoint where weex version is 0.20.1

### ISSUE THREAD

**Issue by bobSir** [apache/incubator-weex#2122]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/taobao/weex/adapter/IWXDebugAdapter;
        at com.alibaba.weex.plugin.loader.utils.WeexSDKUtil$WeexAdapters.<clinit>(WeexSDKUtil.java:145)
        at com.alibaba.weex.plugin.loader.utils.WeexSDKUtil.<clinit>(WeexSDKUtil.java:129)
        at com.alibaba.weex.plugin.loader.utils.WeexSDKUtil.isValidAdapterType(WeexSDKUtil.java:98)
        at com.alibaba.weex.plugin.loader.WeexPluginContainer.loadAdapters(WeexPluginContainer.java:235)
        at com.alibaba.weex.plugin.loader.WeexPluginContainer$1.run(WeexPluginContainer.java:70)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.adapter.IWXDebugAdapter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.fund.weex.fundandroidweex-9lrnKSxHwkRZl1lLhN9BnA==/base.apk"],nativeLibraryDirectories=[/data/app/com.fund.weex.fundandroidweex-9lrnKSxHwkRZl1lLhN9BnA==/lib/arm, /data/app/com.fund.weex.fundandroidweex-9lrnKSxHwkRZl1lLhN9BnA==/base.apk!/lib/armeabi, /system/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.alibaba.weex.plugin.loader.utils.WeexSDKUtil$WeexAdapters.<clinit>(WeexSDKUtil.java:145) 
        at com.alibaba.weex.plugin.loader.utils.WeexSDKUtil.<clinit>(WeexSDKUtil.java:129) 
        at com.alibaba.weex.plugin.loader.utils.WeexSDKUtil.isValidAdapterType(WeexSDKUtil.java:98) 
        at com.alibaba.weex.plugin.loader.WeexPluginContainer.loadAdapters(WeexPluginContainer.java:235) 
        at com.alibaba.weex.plugin.loader.WeexPluginContainer$1.run(WeexPluginContainer.java:70) 
        at java.lang.Thread.run(Thread.java:784)

**Comment by YorkShen** [comment]
It seems like this is caused by `WeexPluginContainer`, what is it?

I don't think it is in weex_sdk.

**Comment by YorkShen** [comment]
As this issue is not updated for a month, I will just close.

Feel free to reopen it if you have further questions.
