### ISSUE TITLE
[Android] WeexCore: server died.  Crash on some vivo mobile models. Weex: v0.20.0.2

### ISSUE THREAD

**Issue by WizardAdrian** [apache/incubator-weex#2201]
```
03-11 15:01:04.189 27806 27939 E WeexCore: failed find class WMBridge
03-11 15:01:04.189 27806 27939 W System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bridge.WMLBridge" on path: DexPathList[[zip file "/data/user/0/com.sdu.didi.gsui/files/hotpatch_hack/hack.apk", zip file "/data/app/com.sdu.didi.gsui-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sdu.didi.gsui-1/lib/arm, /data/app/com.sdu.didi.gsui-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-11 15:01:04.216 27806 27939 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-11 15:01:04.216 27806 27939 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-11 15:01:04.216 27806 27939 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-11 15:01:04.216 27806 27939 W System.err: 	at java.lang.Runtime.nativeLoad(Native Method)
03-11 15:01:04.216 27806 27939 W System.err: 	at java.lang.Runtime.doLoad(Runtime.java:1072)
03-11 15:01:04.216 27806 27939 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:987)
03-11 15:01:04.216 27806 27939 W System.err: 	at java.lang.System.loadLibrary(System.java:1562)
03-11 15:01:04.216 27806 27939 W System.err: 	at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:140)
03-11 15:01:04.216 27806 27939 W System.err: 	at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:226)
03-11 15:01:04.216 27806 27939 W System.err: 	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
03-11 15:01:04.216 27806 27939 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
03-11 15:01:04.217 27806 27939 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-11 15:01:04.217 27806 27939 W System.err: 	at android.os.Looper.loop(Looper.java:154)
03-11 15:01:04.217 27806 27939 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-11 15:01:05.299 27791 27951 W Settings: Setting auto_time has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
03-11 15:01:05.614 27806 27806 W System  : ClassLoader referenced unknown path: /system/app/WebViewGoogle/lib/arm
03-11 15:01:05.615 27806 27806 W System  : ClassLoader referenced unknown path: /oem/lib
03-11 15:01:05.615 27806 27939 E WeexCore: initFromParam is running 
03-11 15:01:05.616 27806 27939 E WeexCore: g_use_single_process is false 
03-11 15:01:05.616 27806 27939 E WeexCore: g_jscSoPath is /data/app/com.sdu.didi.gsui-1/lib/arm 
03-11 15:01:05.616 27806 27939 E WeexCore: g_jssSoPath is /data/app/com.sdu.didi.gsui-1/lib/arm/libweexjss.so 
03-11 15:01:05.616 27806 27939 E WeexCore: g_crashFilePath is /data/user/0/com.sdu.didi.gsui/app_crash 
03-11 15:01:05.616 27806 27939 E WeexCore: g_jssIcuPath is /system/usr/icu/icudt56l.dat 
03-11 15:01:05.616 27806 27939 E WeexCore: lib_ld_path is /data/app/com.sdu.didi.gsui-1/lib/arm:/data/app/com.sdu.didi.gsui-1/base.apk!/lib/armeabi-v7a 
03-11 15:01:05.617 27806 27806 D ApplicationLoaders: ignored Vulkan layer search path /system/app/WebViewGoogle/lib/arm:/system/app/WebViewGoogle/WebViewGoogle.apk!/lib/armeabi-v7a:/oem/lib:/system/lib:/vendor/lib for namespace 0xf4ddd090
03-11 15:01:05.620 27806 27806 I WebViewFactory: Loading com.google.android.webview version 55.0.2883.91 (code 288309150)
03-11 15:01:05.669 27806 27939 E WeexCore: xxx set_core_side is runing and 0xcff03000
03-11 15:01:05.669 27806 27939 E WeexCore: ScriptBridgeInMultiProcess
03-11 15:01:05.669 27806 27939 E WeexCore: MultiProcessAndSoInitializer IS IN init
03-11 15:01:05.669 27806 27939 E WeexCore: RegisterIPCCallback is running
03-11 15:01:05.669 27806 27939 E WeexCore: RegisterIPCCallback is running2
03-11 15:01:05.669 27806 27939 E WeexCore: WeexJSConnection g_crashFileName: /data/user/0/com.sdu.didi.gsui/app_crash/crash_dump.log
03-11 15:01:05.693 27806 27939 E WeexCore: startupPie :1
03-11 15:01:05.704 27996 27996 E WeexCore: weexcore fork child success
03-11 15:01:05.716 27806 27806 I cr_LibraryLoader: Time to load native libraries: 8 ms (timestamps 9120-9128)
03-11 15:01:05.716 27806 27806 I cr_LibraryLoader: Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
03-11 15:01:05.726 27806 27806 I cr_LibraryLoader: Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
03-11 15:01:05.727 27806 27806 I chromium: [INFO:library_loader_hooks.cc(163)] Chromium logging enabled: level = 0, default verbosity = 0
03-11 15:01:05.744 27806 27806 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
03-11 15:01:05.767 27806 27806 I Adreno  : QUALCOMM build                   : e897062, I12c3c6f3ff
03-11 15:01:05.767 27806 27806 I Adreno  : Build Date                       : 10/31/17
03-11 15:01:05.767 27806 27806 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
03-11 15:01:05.767 27806 27806 I Adreno  : Local Branch                     : 
03-11 15:01:05.767 27806 27806 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.01.02.269.051
03-11 15:01:05.767 27806 27806 I Adreno  : Remote Branch                    : NONE
03-11 15:01:05.767 27806 27806 I Adreno  : Reconstruct Branch               : NOTHING
03-11 15:01:05.872 27806 27806 I insight : Start chromium engine complete: 278 ms
03-11 15:01:05.918 27996 27996 I jsengine: mainstartup
03-11 15:01:06.022 27806 27939 E WeexCore: ScriptBridgeInMultiProcess finish cfb17200 0
03-11 15:01:06.037 27996 28016 E WeexCore: xxx set_core_side is runing and 0xea696120
03-11 15:01:06.102 27806 28013 D SensorManager: sensorCTSV isCtsVerifier false
03-11 15:01:06.102 27806 28013 D SensorManager: sensorCTSV isCtsVerifier false
03-11 15:01:06.102 27806 28013 D SensorManager: sensorCTSV isCtsVerifier false
03-11 15:01:06.102 27806 28013 D SensorManager: sensorCTSV isCtsVerifier false
03-11 15:01:06.119 27996 28016 E WeexCore: start weex queue init
03-11 15:01:06.119 27996 28025 E WeexCore: WeexRuntime is running and mode is multiProcess
03-11 15:01:06.129 27996 28025 E jsengine: initICUEnv patch:/system/usr/icu/icudt56l.dat
03-11 15:01:06.133 27806 28023 D SensorManager: sensorCTSV isCtsVerifier false
03-11 15:01:06.133 27806 28023 D SensorManager: sensorCTSV isCtsVerifier false
03-11 15:01:06.157 27806 28013 E SensorManager: sensor or listener is null
03-11 15:01:06.168 27806 28023 E SensorManager: sensor or listener is null
03-11 15:01:06.295 27806 27994 E WeexCore: server died
```

**Comment by Darin726** [comment]
从日志来看子进程发生 crash 不会导致主进程 crash.  你本地能复现这个问题吗, 如果能复现, 是否方便提供一下 /data/user/0/com.sdu.didi.gsui/app_crash/crash_dump.log 这个文件让我们分析一下

**Comment by Darin726** [comment]
你们是否有适配 IWXJSExceptionAdapter 来获取 serverDie 的异常信息?  https://github.com/apache/incubator-weex/blob/master/android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java#L1351

**Comment by YorkShen** [comment]
As this issue is not updated for quite a while, I will just close it. Feel free to reopen it any time.
