### ISSUE TITLE
jsframework has no such api

### ISSUE THREAD

**Issue by chengsan** [apache/incubator-weex#2231]
weex_sdk:0.20.0.2
weex_inspector:0.22.1.3
无法调试，界面加载是空白，报 call [__WEEX_CALL_JAVASCRIPT__] error: jsframework has no such ap，不进行调试，直接运行APP是OK的，然后原生控制台报如下错误：
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err: java.lang.AbstractMethodError: abstract method "int com.taobao.weex.common.IWXBridge.callLayout(java.lang.String, java.lang.String, int, int, int, int, int, int, int)"
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.bridge.WXDebugJsBridge.jsHandleCallCreateFinish(Native Method)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.devtools.inspector.protocol.module.WxDebug$6.run(WxDebug.java:216)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.handleCallback(Handler.java:755)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Looper.loop(Looper.java:156)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err: java.lang.AbstractMethodError: abstract method "int com.taobao.weex.common.IWXBridge.callLayout(java.lang.String, java.lang.String, int, int, int, int, int, int, int)"
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.bridge.WXDebugJsBridge.jsHandleCallCreateFinish(Native Method)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.devtools.inspector.protocol.module.WxDebug$6.run(WxDebug.java:216)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.handleCallback(Handler.java:755)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Looper.loop(Looper.java:156)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err: java.lang.AbstractMethodError: abstract method "int com.taobao.weex.common.IWXBridge.callLayout(java.lang.String, java.lang.String, int, int, int, int, int, int, int)"
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.bridge.WXDebugJsBridge.jsHandleCallCreateFinish(Native Method)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.devtools.inspector.protocol.module.WxDebug$6.run(WxDebug.java:216)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.handleCallback(Handler.java:755)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-21 16:33:45.576 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Looper.loop(Looper.java:156)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err: java.lang.AbstractMethodError: abstract method "int com.taobao.weex.common.IWXBridge.callLayout(java.lang.String, java.lang.String, int, int, int, int, int, int, int)"
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.bridge.WXDebugJsBridge.jsHandleCallCreateFinish(Native Method)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.devtools.inspector.protocol.module.WxDebug$6.run(WxDebug.java:216)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.handleCallback(Handler.java:755)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.Looper.loop(Looper.java:156)
2019-03-21 16:33:45.577 16492-16540/com.longrise.sgp.phone W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by fanlvwen** [comment]
请问你解决了吗

**Comment by chengsan** [comment]
> 请问你解决了吗

没

**Comment by fanlvwen** [comment]
https://github.com/apache/incubator-weex/issues/2242
你看一下我这个issue，
你的chrome里面显示的js framework是什么版本的，最新的是0.29.5了，我问了阿里的人他们说no such api原因的js framework版本太低了


还有你开启 js debug的时候，
![image](https://user-images.githubusercontent.com/36951996/54962826-51aafc80-4fa1-11e9-97e9-172dc01cd57e.png)这个你填的什么

**Comment by chengsan** [comment]
> #2242
> 你看一下我这个issue，
> 你的chrome里面显示的js framework是什么版本的，最新的是0.29.5了，我问了阿里的人他们说no such api原因的js framework版本太低了
> 
> 还有你开启 js debug的时候，
> ![image](https://user-images.githubusercontent.com/36951996/54962826-51aafc80-4fa1-11e9-97e9-172dc01cd57e.png)这个你填的什么

JS framework版本是0.29.0  地址是有的，也是对的

**Comment by fanlvwen** [comment]
跟我一样的问题，官方说是js framework版本低，可是我依赖的weex sdk和weex inspector都是最新的0.20.3.0-beta，官方说git上的playground直接运行没问题，可是我拉下来，android和ios都debug 不了，输入http://192.168.2.236:8089/weex/vue/index.js页面能加载出来，点击跳别的页面就一直loading，就运行不下去了，再回来首页再点击就报你这个错

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Unable to debug, the interface loading is blank, report call [WEEX_CALL_JAVASCRIPT] error: jsframework has no such ap, no debugging, directly run APP is OK, then the native console reports the following error

I think this is a bug about dev-tool, you should ask it in the [weex-toolkit](https://github.com/weexteam/weex-toolkit), not this repos.
