### ISSUE TITLE
win 开发环境报错 Error: Cannot find module 'postcss'

### ISSUE THREAD

**Issue by Yalun-Yong** [apache/incubator-weex#2315]
D:\Android\project\weex\demo1\weexapp>weex doctor
Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Administrator\.wx\modules\node_modules\_postcss-plugin-weex@0.1.7@postcss-plugin-weex\src\index.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Administrator\.wx\modules\node_modules\_@weex-cli_compile@2.0.0-beta.2@@weex-cli\compile\src\WeexBuilder.ts:7:0)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by erha19** [comment]
@Yalun-Yong try `weex repair @weex-cli/compile`.

**Comment by YorkShen** [comment]
It seems this issue is solved, I will close it.

Feel free to reopen it if you have further questions.
