### ISSUE TITLE
[Dev-tool] After booting by weex run ios, run through xcode debugging, and occasionally crash where weex CLI version 2.0.0-beta.25!

### ISSUE THREAD

**Issue by hponiang** [apache/incubator-weex#2383]
## Describe the bug

After booting by weex run ios, run through xcode debugging, and occasionally crash, the prompt is as follows
## Environment
模拟器  mac os 10.14.4
weex CLI version 2.0.0-beta.25!

## Screenshots

`Hotreload server is actived, enjoy your develop
Type Ctrl+C to exist
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/Users/dt/.wx/modules/node_modules/_ws@6.2.1@ws/lib/websocket.js:329:19)
    at FSWatcher.filesWatcher.fs.watch (/Users/dt/.wx/modules/node_modules/_@weex-cli_run@2.0.0-beta.21@@weex-cli/run/lib/base/runner.js:82:20)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/Users/dt/.wx/modules/node_modules/_ws@6.2.1@ws/lib/websocket.js:329:19)
    at FSWatcher.filesWatcher.fs.watch (/Users/dt/.wx/modules/node_modules/_@weex-cli_run@2.0.0-beta.21@@weex-cli/run/lib/base/runner.js:82:20)
    at FSWatcher.emit (events.js:189:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
Error: stdout maxBuffer exceeded
    at PassThrough.stream.on (/Users/dt/.wx/core/node_modules/_get-stream@3.0.0@get-stream/index.js:30:12)
    at PassThrough.emit (events.js:194:15)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at PassThrough.Readable.push (_stream_readable.js:220:10)
    at PassThrough.Transform.push (_stream_transform.js:151:32)
    at PassThrough.afterTransform (_stream_transform.js:92:10)
    at PassThrough._transform (_stream_passthrough.js:42:3)
    at PassThrough.Transform._read (_stream_transform.js:190:10)
    at PassThrough.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at PassThrough.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:667:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)`

**Comment by hponiang** [comment]
![image](https://user-images.githubusercontent.com/8768585/56939503-554f1780-6b3b-11e9-9f72-e54cd75ab818.png)

**Comment by hponiang** [comment]
@jakswa

**Comment by YorkShen** [comment]
As this is a problem of weex-toolkit, you should ask in [their repo](https://github.com/weexteam/weex-toolkit), not here.

Thanks for your cooperation.
