### ISSUE TITLE
[Android] java.lang.NoSuchFieldError:

### ISSUE THREAD

**Issue by flyminiboy** [apache/incubator-weex#2401]
java.lang.NoSuchFieldError:
com.taobao.weex.utils.LogLevel.ERROR
	at com.taobao.weex.utils.WXLogUtils.e(WXLogUtils.java:189)
	at com.taobao.weex.WXSDKEngine.initialize(WXSDKEngine.java:164)

OPPO-N5116

**Comment by YorkShen** [comment]
Update to the latest version and try again, thanks.
