### ISSUE TITLE
[Dev-tool] Mac,New project error after upgrading to the latest version（Error: module is locked）

### ISSUE THREAD

**Issue by lanyi90822** [apache/incubator-weex#2452]
Error: module is locked
    at Object.<anonymous> (/Users/zhangbin/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.27@@weex-cli/core/src/toolbox/installer-tools.ts:159:19)
    at Generator.next (<anonymous>)
    at <anonymous> (/Users/zhangbin/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.27@@weex-cli/core/lib/toolbox/installer-tools.js:7:71)
    at new Promise (<anonymous>)
    at __awaiter (/Users/zhangbin/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.27@@weex-cli/core/lib/toolbox/installer-tools.js:3:12)
    at Object.install (/Users/zhangbin/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.27@@weex-cli/core/src/toolbox/installer-tools.ts:151:79)
    at <anonymous> (/Users/zhangbin/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.27@@weex-cli/core/src/cli/cli.ts:416:26)
    at Generator.next (<anonymous>)
    at <anonymous> (/Users/zhangbin/.wx/core/node_modules/_@weex-cli_core@2.0.0-beta.27@@weex-cli/core/lib/cli/cli.js:7:71)
    at new Promise (<anonymous>)

**Comment by YorkShen** [comment]
From the stacktrace you provided, I think it's the problem of Weex CLI.

Please ask this question [Weex CLI repo](https://github.com/weexteam/weex-toolkit/issues).
