### ISSUE TITLE
./node_modules/weex-ui/index.js\nModule build failed: Error: Cannot find module \'babel-core\'

### ISSUE THREAD

**Issue by denghuishi0** [apache/incubator-weex#2490]
import {
        WxcLoading
    } from 'weex-ui';

打包
weex compile src dist
[ './node_modules/weex-ui/index.js\nModule build failed: Error: Cannot find module \'babel-core\'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_babel-loader@7.1.5@babel-loader\\lib\\index.js:3:13)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n
   at require (internal/modules/cjs/helpers.js:20:18)\n    at loadLoader (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_loader-runner@2.3.1@loader-runner\\lib\\loadLoader.js:13:17)\n    at iteratePitchingLoaders (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_loader-runner@2.3.1@loader-runner\\lib\\LoaderRunner.js:169:2)\n    at runLoaders (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_loader-runner@2.3.1@loader-runner\\lib\\LoaderRunner.js:362:2)\n    at NormalModule.doBuild (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_webpack@3.12.0@webpack\\lib\\NormalModule.js:182:3)\n    at NormalModule.build (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_webpack@3.12.0@webpack\\lib\\NormalModule.js:275:15)\n    at Compilation.buildModule (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_webpack@3.12.0@webpack\\lib\\Compilation.js:157:10)\n    at factoryCallback (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_webpack@3.12.0@webpack\\lib\\Compilation.js:348:12)\n    at factory (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_webpack@3.12.0@webpack\\lib\\NormalModuleFactory.js:243:5)\n    at applyPluginsAsyncWaterfall (C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_webpack@3.12.0@webpack\\lib\\NormalModuleFactory.js:94:13)\n    at C:\\Users\\Shidh\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_tapable@0.2.9@tapable\\lib\\Tapable.js:268:11\n @ C:/Users/Shidh/AppData/Roaming/npm/node_modules/weex-toolkit/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/script-loader.js!C:/Users/Shidh/AppData/Roaming/npm/node_modules/weex-toolkit/node_modules/_weex-vue-loader@0.7.0@weex-vue-loader/lib/selector.js?type=script&index=0!./src/components/base.vue 12:0-14:17\n @ ./src/components/base.vue?entry=true' ]

**Comment by YorkShen** [comment]
Again, this is something about weex-cli, you should ask question in [weex-cli](https://github.com/weexteam/CLI-for-Apache-Weex), not here.
