### ISSUE TITLE
java.lang.ExceptionInInitializerError at com.taobao.weex.WXSDKEngine.

### ISSUE THREAD

**Issue by wuhh2016** [apache/incubator-weex#2503]
java.lang.ExceptionInInitializerError
at com.taobao.weex.WXSDKEngine.$jacocoInit(SourceFile)
at com.taobao.weex.WXSDKEngine.<clinit>(SourceFile)
at com.test.app.SomeClass$1.run(SourceFile:132)// WXSDKEngine.addCustomOptions
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5845)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
Caused by: java.util.ConcurrentModificationException
at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
at java.util.Hashtable$EntryIterator.next(Hashtable.java:776)
at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.a(SourceFile:56)
at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.a(SourceFile:37)
at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(SourceFile:29)
... 10 more

**Comment by wuhh2016** [comment]
java.lang.ExceptionInInitializerError
at org.jacoco.agent.rt.internal_8ff85ea.Offline.a(SourceFile:51)
at com.taobao.weex.WXSDKEngine.$jacocoInit(SourceFile)
at com.taobao.weex.WXSDKEngine.<clinit>(SourceFile)
at com.taobao.weex.WXSDKEngine.addCustomOptions(SourceFile)
at com.test.app.SomeClass$1.run(SourceFile:132)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5845)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
Caused by: java.util.ConcurrentModificationException
at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
at java.util.Hashtable$EntryIterator.next(Hashtable.java:776)
at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.a(SourceFile:56)
at org.jacoco.agent.rt.internal_8ff85ea.ConfigLoader.a(SourceFile:37)
at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(SourceFile:29)
... 12 more

**Comment by YorkShen** [comment]
Please update to the latest version of weex, I think this problem is solved months ago.

Feel free to reopen it if there is still problems( *I only response to issues that are open*).
