### ISSUE TITLE
[Android][iOS][Dev-tool] Unexpected behavior when xx where weex version is v2.0.0-beta.21

### ISSUE THREAD

**Issue by Api80** [apache/incubator-weex#2510]
执行 weex run android 时报错

最开始执行weex run android 提示 升级2.0.0-beta.29  后来选的No  再执行 weex run android 就变成这样了

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\DELL\.wx\modules\node_modules\_@weex-cli_debug@2.0.0-beta.27@@weex-cli\debug\commands\debug.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.loadModule (C:\Users\DELL\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.26@@weex-cli\core\src\loaders\module-loader.ts:14:9)
    at Object.loadCommandFromFile (C:\Users\DELL\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.26@@weex-cli\core\src\loaders\command-loader.ts:43:22)
    at plugin.commands.plugin.commands.concat.ramda_1.map.file (C:\Users\DELL\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.26@@weex-cli\core\src\loaders\plugin-loader.ts:57:18)
    at _map (C:\Users\DELL\.wx\core\node_modules\_ramda@0.25.0@ramda\src\internal\_map.js:6:19)

**Comment by YorkShen** [comment]
1. Please update to the latest version of weex.
2. This is a problem about [CLI](CLI-for-Apache-Weex), please ask question in the right place.
