### ISSUE TITLE
[Android][Dev-tool] Unexpected render error:1001 when launch app  where weex version is 0.24.0

### ISSUE THREAD

**Issue by hupanfeng** [apache/incubator-weex#2538]
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/base.apk
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_dependencies_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_0_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_1_apk.apk
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_2_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_3_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_4_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_5_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_6_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_7_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_8_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
W/System: in loadDexFile: /data/app/com.cztech.jdyw-1/split_lib_slice_9_apk.apk
W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm64 --instruction-set-features=smp,a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/com.cztech.jdyw-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm64/data@app@com.cztech.jdyw-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
I/InstantRun: starting instant run server: is main process
E/WXSDKEngine: WXEnvironment.sApplication is null
E/weex: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.cztech.jdyw/files/libweexcorebk1.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.load(Runtime.java:332)
        at java.lang.System.load(System.java:1069)
        at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:405)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:154)
        at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:227)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:171)
        at android.os.HandlerThread.run(HandlerThread.java:61)
D/CLog: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.cztech.jdyw/files/libweexcorebk1.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.load(Runtime.java:332)
        at java.lang.System.load(System.java:1069)
        at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:405)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:154)
        at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:227)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:171)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/weex: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.cztech.jdyw/files/libweexcorebk1.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.load(Runtime.java:332)
        at java.lang.System.load(System.java:1069)
        at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:405)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.unZipSelectedFiles(WXSoInstallMgrSdk.java:501)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:168)
        at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:227)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:171)
        at android.os.HandlerThread.run(HandlerThread.java:61)
D/CLog: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.cztech.jdyw/files/libweexcorebk1.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.load(Runtime.java:332)
        at java.lang.System.load(System.java:1069)
        at com.taobao.weex.utils.WXSoInstallMgrSdk._loadUnzipSo(WXSoInstallMgrSdk.java:405)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.unZipSelectedFiles(WXSoInstallMgrSdk.java:501)
        at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:168)
        at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:227)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:171)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by YorkShen** [comment]
The log is pretty straightforward. 

> "/data/data/com.cztech.jdyw/files/libweexcorebk1.so" is 32-bit instead of 64-bit

We are working on 64 bit supporting, but Weex only supports 32 bit now. Ref #2389 to see time schedule of 64 bit supporting. We will announce it in the [mail list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list) as well.
