### ISSUE TITLE
[Android] updateAttrs got NullPointerException where weex version is 0.24.0

### ISSUE THREAD

**Issue by xdmaolei** [apache/incubator-weex#2630]
Stacktrace:

> java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.Map.putAll(java.util.Map)' on a null object reference
	at com.taobao.weex.dom.WXAttr.putAll(WXAttr.java:443)
	at com.taobao.weex.ui.action.BasicComponentData.addAttr(BasicComponentData.java:78)
	at com.taobao.weex.ui.component.basic.WXBasicComponent.addAttr(WXBasicComponent.java:117)
	at com.taobao.weex.ui.action.GraphicActionUpdateAttr.<init>(GraphicActionUpdateAttr.java:42)
	at com.taobao.weex.bridge.WXBridgeManager.callUpdateAttrs(WXBridgeManager.java:2885)
	at com.taobao.weex.bridge.WXBridge.callUpdateAttrs(WXBridge.java:551)
	at com.taobao.weex.base.SystemMessageHandler.nativeRunWork(Native Method)
	at com.taobao.weex.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:104)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.os.HandlerThread.run(HandlerThread.java:65)

maybe caused by multi-thread

**Comment by YorkShen** [comment]
Well, this is wired.

There is a NPE protection as you can [see](https://github.com/apache/incubator-weex/blob/584374e5ef256545f6230159ed0c2c18efc4e6c1/android/sdk/src/main/java/com/taobao/weex/dom/WXAttr.java#L440-L443)

Anymore log? like the crash happens in which thread ?
