### ISSUE TITLE
[Android][AAB]使用Google Play的AAB打包，出现页面渲染失败

### ISSUE THREAD

**Issue by wind24** [apache/incubator-weex#2819]
我们最近使用Google推荐的Android Application Bundle打包，但是发现Weex页面都没法显示了，正常打包的APK版本是可以显示的。具体的错误信息如下：

2019-08-13 11:26:16.550 28364-28476/com.hellotalk W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/base.apk", zip file "/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk", zip file "/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.ja.apk", zip file "/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.xxhdpi.apk", zip file "/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.zh.apk"],nativeLibraryDirectories=[/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/lib/arm64, /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/base.apk!/lib/arm64-v8a, /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.ja.apk!/lib/arm64-v8a, /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.xxhdpi.apk!/lib/arm64-v8a, /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.zh.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
2019-08-13 11:26:16.551 28364-28476/com.hellotalk W/System.err:     at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:153)
2019-08-13 11:26:16.551 28364-28476/com.hellotalk W/System.err:     at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:226)
2019-08-13 11:26:16.551 28364-28476/com.hellotalk W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:71)
2019-08-13 11:26:16.555 28364-28476/com.hellotalk E/weex: tryUseRunTimeApi ? false
2019-08-13 11:26:16.632 28364-28476/com.hellotalk W/weex: WXComponentRegistry Duplicate the Module name: navigator
2019-08-13 11:26:16.641 28364-28476/com.hellotalk W/weex: WXComponentRegistry Duplicate the Module name: webview
2019-08-13 11:26:16.647 28364-28476/com.hellotalk W/weex: app AvailMemory ---->>>1662
2019-08-13 11:26:16.656 28364-28476/com.hellotalk E/weex: weexjss's Path is /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libweexjss.so but file does not exist
2019-08-13 11:26:18.135 28364-28476/com.hellotalk E/weex: test-> findLibJssRealPath /data/user/0/com.hellotalk/cache/libweexjss.so
2019-08-13 11:26:18.141 28364-28476/com.hellotalk E/weex: getLibLdPath is /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/lib/arm64:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/base.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.ja.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.xxhdpi.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.zh.apk!/lib/arm64-v8a
2019-08-13 11:26:18.141 28364-28476/com.hellotalk E/weex: JavaScriptCore's Path is /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libJavaScriptCore.so but file does not exist
2019-08-13 11:26:19.759 28364-28476/com.hellotalk E/weex: findLibJscRealPath /data/user/0/com.hellotalk/cache/libJavaScriptCore.so
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/weex: getUseSingleProcess is running false
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:197,g_use_single_process is false 
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/weex: getLibJscPath is running /data/user/0/com.hellotalk/cache
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:232,g_jscSoPath is /data/user/0/com.hellotalk/cache 
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/weex: getLibJssPath is running /data/user/0/com.hellotalk/cache/libweexjss.so
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:245,g_jssSoPath is /data/user/0/com.hellotalk/cache/libweexjss.so 
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:257,g_crashFilePath is /data/user/0/com.hellotalk/app_crash 
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/weex: getLibIcuPath is running /apex/com.android.runtime/etc/icu/icudt63l.dat
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:270,g_jssIcuPath is /apex/com.android.runtime/etc/icu/icudt63l.dat 
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/weex: getLibJsbPath is running /data/data/com.hellotalk/cache/weex/libs/weexjsb/arm64-v8a/libweexjsb.so
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:283,g_jsbSoPath is /data/data/com.hellotalk/cache/weex/libs/weexjsb/arm64-v8a/libweexjsb.so 
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/weex: getLibLdPath is running /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/lib/arm64:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/base.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.ja.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.xxhdpi.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.zh.apk!/lib/arm64-v8a
2019-08-13 11:26:19.760 28364-28476/com.hellotalk E/WeexCore: params_utils.cpp:297,lib_ld_path is /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/lib/arm64:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/base.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.ja.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.xxhdpi.apk!/lib/arm64-v8a:/data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.zh.apk!/lib/arm64-v8a 
2019-08-13 11:26:19.762 28364-28476/com.hellotalk E/WeexCore: setDebugMode  2 
2019-08-13 11:26:19.762 28364-28476/com.hellotalk E/WeexCore: script_bridge.h:178,xxx set_core_side is runing and 0x7420783db0
2019-08-13 11:26:19.762 28364-28476/com.hellotalk E/WeexCore: script_bridge_in_multi_process.cpp:1004,ScriptBridgeInMultiProcess
2019-08-13 11:26:19.762 28364-28476/com.hellotalk E/WeexCore: multi_process_and_so_initializer.cpp:38,MultiProcessAndSoInitializer IS IN init
2019-08-13 11:26:19.762 28364-28476/com.hellotalk E/WeexCore: weex_js_connection.cpp:146,WeexJSConnection g_crashFileName: /data/user/0/com.hellotalk/app_crash/crash_dump.log
2019-08-13 11:26:19.761 28364-28364/com.hellotalk W/WeexJSBridgeThr: type=1400 audit(0.0:6897): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=19513 scontext=u:r:untrusted_app_27:s0:c223,c256,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file
2019-08-13 11:26:19.764 28364-28476/com.hellotalk E/WeexCore: weex_js_connection.cpp:266,startupPie :1
2019-08-13 11:26:52.609 28364-28476/com.hellotalk E/WeexCore: weex_js_connection.cpp:306,WeexJSConnection catch: spinWaitPeer timeout
2019-08-13 11:26:52.609 28364-28686/com.hellotalk E/WeexCore: weex_js_connection.cpp:192,server died
2019-08-13 11:26:52.609 28364-28476/com.hellotalk E/WeexCore: multi_process_and_so_initializer.cpp:47,JSFramwork init start sender is null
2019-08-13 11:26:52.608 28364-28364/com.hellotalk W/WeexJSBridgeThr: type=1400 audit(0.0:6899): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=19513 scontext=u:r:untrusted_app_27:s0:c223,c256,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file
2019-08-13 11:26:52.609 28364-28476/com.hellotalk E/WeexCore: weex_js_connection.cpp:146,WeexJSConnection g_crashFileName: /data/user/0/com.hellotalk/app_crash/crash_dump.log
2019-08-13 11:26:52.610 28364-28476/com.hellotalk E/WeexCore: weex_js_connection.cpp:266,startupPie :1
2019-08-13 11:26:52.883 28364-28364/com.hellotalk E/weex: idle from create instance cache size is 0
2019-08-13 11:26:52.887 28364-28364/com.hellotalk E/HTWeexJsKit: loadJs begin url:https://ali-hk-cdn.hellotalk8.com/learning_page/test/home_1.0.0_752cf39427a92519.js?
2019-08-13 11:26:52.887 28364-28364/com.hellotalk E/HTWeexJsKit: loadJs cache:/storage/emulated/0/hellotalk/weex_page/-813871689
2019-08-13 11:26:52.887 28364-28364/com.hellotalk E/HTWeexJsKit: loadJs cache exists.
2019-08-13 11:26:52.894 28364-28364/com.hellotalk E/weex: onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
2019-08-13 11:26:52.895 28364-28364/com.hellotalk W/weex: Warning :Component tree has not build completely, onActivityResume can not be call!
2019-08-13 11:26:53.028 28364-28364/com.hellotalk W/weex: Warning :Component tree has not build completely, onActivityResume can not be call!
2019-08-13 11:26:53.079 28364-28364/com.hellotalk E/HTWeexView: WEEX onException errCode:-1001,msg:degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
2019-08-13 11:26:53.079 28364-28364/com.hellotalk E/HTWeexView: onRenderError
2019-08-13 11:26:53.080 28364-28364/com.hellotalk E/WeexOpenPageHelper: netRefresh  
2019-08-13 11:26:53.189 28364-28364/com.hellotalk E/WeexOpenPageHelper: exchangeOpenPage result=WeexCache{cacheUrl='https://ali-hk-cdn.hellotalk8.com/learning_page/test/home_1.0.0_752cf39427a92519.js?', key='hellotalk://htgotopage/learn_tab', assetPath=''}
2019-08-13 11:26:53.190 28364-28364/com.hellotalk E/HTWeexJsKit: removeCache ret:true
2019-08-13 11:26:53.191 28364-28364/com.hellotalk E/HTWeexJsKit: loadJs begin url:https://ali-hk-cdn.hellotalk8.com/learning_page/test/home_1.0.0_752cf39427a92519.js?
2019-08-13 11:26:53.191 28364-28364/com.hellotalk E/HTWeexJsKit: loadJs cache:/storage/emulated/0/hellotalk/weex_page/-813871689
2019-08-13 11:26:53.193 28364-28736/com.hellotalk E/HTWeexJsKit: loadJs start download task
2019-08-13 11:26:53.193 28364-28736/com.hellotalk E/HTWeexJsKit: downloadUrl url:https://ali-hk-cdn.hellotalk8.com/learning_page/test/home_1.0.0_752cf39427a92519.js?
2019-08-13 11:26:53.411 28364-28736/com.hellotalk E/HTWeexJsKit: downloadUrl has data:true
2019-08-13 11:26:53.411 28364-28736/com.hellotalk E/HTWeexJsKit: has content-md5
2019-08-13 11:26:53.413 28364-28364/com.hellotalk E/HTWeexJsKit: loadJs download finish cache exists:true
2019-08-13 11:26:53.417 28364-28364/com.hellotalk E/weex: onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
2019-08-13 11:26:53.417 28364-28364/com.hellotalk E/HTWeexView: WEEX onException errCode:-1001,msg:degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
2019-08-13 11:26:53.417 28364-28364/com.hellotalk E/HTWeexView: onRenderError
2019-08-13 11:26:53.417 28364-28364/com.hellotalk E/HTLearnWeexView: rendered= false   statusView= 1

**Comment by LanYun** [comment]
这个问题应该是64位so库本身的问题吧？我直接用64位so库跑在64位的机子上也是出现渲染点击响应异常，日志也跟上面类似

**Comment by YorkShen** [comment]
Weex initlization failed due to there is no corresponding shared library.

```
JavaScriptCore's Path is /data/app/com.hellotalk-DLJZ9th0DAMmVtmO8JE5Iw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libJavaScriptCore.so but file does not exist
```

Maybe you should check the above log.
