### ISSUE TITLE
W/NetworkEventReporter: java.lang.ClassNotFoundException: com.taobao.weex.devtools.inspector.network.NetworkEventReporterImpl

### ISSUE THREAD

**Issue by huobaiyu** [apache/incubator-weex#2843]
不知道这个class 在哪里实现的？
W/NetworkEventReporter: java.lang.ClassNotFoundException: com.taobao.weex.devtools.inspector.network.NetworkEventReporterImpl
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.taobao.weex.devtools.inspector.network.NetworkEventReporterManager.get(NetworkEventReporterManager.java:232)
        at com.supercloud.education.weex.util.WSEventReporter.<init>(WSEventReporter.java:30)
        at com.supercloud.education.weex.util.WSEventReporter.newInstance(WSEventReporter.java:25)
        at com.supercloud.education.weex.adapter.DefaultWebSocketAdapter.connect(DefaultWebSocketAdapter.java:35)
        at com.taobao.weex.appfram.websocket.WebSocketModule.WebSocket(WebSocketModule.java:91)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:46)
        at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:48)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

W/NetworkEventReporter: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.weex.devtools.inspector.network.NetworkEventReporterImpl" on path: DexPathList[[zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/base.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_resources_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/base.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 19 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.supercloud.education.cschool-x80eOO87xlGl5HYpucMtCQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
2019-08-21 15:41:07.880 8405-8405/com.supercloud.education.cschool W/NetworkEventReporter:     at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        		... 5 more

build.gradle 引入了以下相关包
implementation group: 'com.taobao.android.weex_inspection', name: 'protocol', version: '1.1.4.1'
    implementation 'com.taobao.android:weex_analyzer:0.1.0.5'
    implementation 'com.taobao.android.weex_inspection:urlconnection_interceptor:1.0.0'

    implementation  'com.squareup.okhttp:okhttp:2.3.0'
    implementation  'com.squareup.okhttp:okhttp-ws:2.3.0'

    implementation group: 'com.taobao.android.weex_inspection', name: 'okhttp_interceptor', version: '1.0.1'

**Comment by YorkShen** [comment]
`com.taobao.weex.devtools.inspector.network.NetworkEvent` is imported from `weex_inspection` for debugging purpose. Currently, weex_inspection is not a part of Apache Weex, so you should either remove the dependency or ask question in their [repo](https://github.com/weexteam/android-devtools-for-Apache-Weex)

**Comment by helixs** [comment]
Weex文档写的太不全了，inspector这个工具新版本并没有自动依赖weex_inspection:protocol这个库
需要添加
`implementation 'com.taobao.android.weex_inspection:protocol:1.1.4.1`
希望能帮助到大家
