### ISSUE TITLE
[Android] wx_create_instance_error isJSFrameworkInit==false reInitCount == 1 where weex version is 0.20.0.2

### ISSUE THREAD

**Issue by wangfengzxz** [apache/incubator-weex#2864]
A little more of users encounted this problem.

java.lang.RuntimeException: degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1
	at com.yit.module.weex.ui.i.onException(WeexFragment.java:1)
	at com.taobao.weex.o.run(WXSDKInstance.java:2)
	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:2)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

This trance is the same type below
java.lang.RuntimeException: degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==true reInitCount == 1
	at com.yit.module.weex.ui.i.onException(WeexFragment.java:1)
	at com.taobao.weex.o.run(WXSDKInstance.java:2)
	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:2)
	at android.os.Handler.handleCallback(Handler.java:793)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by YorkShen** [comment]
1. There is nothing we can do with such little infomration.
1. Checkout out Weex 0.28 and give it a try.
2. If this still bothers you and you find a solution, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8). 
3. As I have a busy schedule, I may read Github issuse months later, but I check mailing list everyday.
