### ISSUE TITLE
[Android] error_code: -1001, degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

### ISSUE THREAD

**Issue by flyminiboy** [apache/incubator-weex#2869]
机型
OPPO   R815T
cpu
联发科 MT6589
内存
1GB
系统版本
4.2.1
分辨率
800x480

weex 版本
0.26.0

必现问题。

**Comment by zsmjhtn** [comment]
Same problem. But no suggestions\issues mentiond in Weex DOC.

**Comment by fengqingyun2008** [comment]
Same problem. But no suggestions\issues mentiond in Weex DOC.
+1

implementation 'com.taobao.android:weex_sdk:0.26.0'
    implementation 'com.taobao.android:weex_inspector:0.24.2.4'
    // PLUGIN GRADLE EXTENSIONS START
    implementation 'com.taobao.android:weexplugin-loader:1.3'
    implementation 'com.taobao.android:weexplugin-processor:1.3'
    annotationProcessor 'com.taobao.android:weexplugin-annotation:1.3'
    // PLUGIN GRADLE EXTENSIONS END

**Comment by YorkShen** [comment]
1. With such little information, there is nothing I can do.
1. Maybe you could try Weex 0.28.
2. If this still bothers you and you find a solution, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8).
3. I have a busy schedule and I can't read Github issue every day, but I check mailing list every day. I am sorry if this bothers you.

**Comment by FightingForDevelop** [comment]
> 1. With such little information, there is nothing I can do.
> 2. Maybe you could try Weex 0.28.
> 3. If this still bothers you and you find a solution, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8).
> 4. I have a busy schedule and I can't read Github issue every day, but I check mailing list every day. I am sorry if this bothers you.

My app occurs many times.
degradeToH5|createInstance fail|wx_create_instance_error[WXBridgeManager] invokeCreateInstance :  template md5 a697118f8fb455f7ada950647fc2e0e9 length 775376 base64 md5 ppcRj4+0VfetqVBkf8Lg6Q== response header {"templateSourceBase64MD5":["ppcRj4+0VfetqVBkf8Lg6Q=="],"templateSourceMD5":["a697118f8fb455f7ada950647fc2e0e9"]}
and

degradeToH5\|createInstance fail\|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

**Comment by YorkShen** [comment]
Try Weex 0.28, thanks.

Even if this is a bug, we will only fix it based on the latest version of Weex.

**Comment by FightingForDevelop** [comment]
> Try Weex 0.28, thanks.
> 
> Even if this is a bug, we will only fix it based on the latest version of Weex.

Yes,this is occur on 0.28

**Comment by FightingForDevelop** [comment]
> Try Weex 0.28, thanks.
> 
> Even if this is a bug, we will only fix it based on the latest version of Weex.

Does weex have compatibility problem,except cpu? Does weex ask android system version?

**Comment by FightingForDevelop** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/data/app/***-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zhaopin.ihr-1/lib/arm, /vendor/lib, /system/lib]]
12-26 15:38:27.054 12104-12170/com.zhaopin.ihr W/System.err:     at com.taobao.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:153)
12-26 15:38:27.054 12104-12170/com.zhaopin.ihr W/System.err:     at com.taobao.weex.WXSDKEngine$1.run(WXSDKEngine.java:224)
12-26 15:38:27.054 12104-12170/com.zhaopin.ihr W/System.err:     at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)
12-26 15:38:27.064 12104-12170/com.zhaopin.ihr W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.taobao.windmill.bundle.bridge.WeexBridge

 app AvailMemory ---->>>1802
12-26 15:38:27.224 12104-12170/com.zhaopin.ihr D/weex: weex JS framework from assets
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr D/weex: [WXBridgeManager] initFrameworkEnv crashFile:/data/data/com.zhaopin.ihr/cache pieSupport:true
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: weexjss's Path is/data/app/com.zhaopin.ihr-1/lib/arm/libweexjss.so
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr D/weex: test-> findLibJssRealPath /data/app/com.zhaopin.ihr-1/lib/arm/libweexjss.so
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr D/weex: getLibLdPath is /data/app/com.zhaopin.ihr-1/lib/arm:/vendor/lib:/system/lib
weex: jsc's Path is/data/app/com.zhaopin.ihr-1/lib/arm/libjsc.so
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: findLibJscRealPath /data/app/com.zhaopin.ihr-1/lib/arm/libjsc.so
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: enableAlarmSignal:true
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: getUseSingleProcess is running false
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/WeexCore: params_utils.cpp:197,g_use_single_process is false 
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: getLibJscPath is running /data/app/com.zhaopin.ihr-1/lib/arm
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/WeexCore: params_utils.cpp:232,g_jscSoPath is /data/app/com.zhaopin.ihr-1/lib/arm 
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: getLibJssPath is running /data/app/com.zhaopin.ihr-1/lib/arm/libweexjss.so
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/WeexCore: params_utils.cpp:245,g_jssSoPath is /data/app/com.zhaopin.ihr-1/lib/arm/libweexjss.so 
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/WeexCore: params_utils.cpp:257,g_crashFilePath is /data/data/com.zhaopin.ihr/app_crash 
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: getLibIcuPath is running /system/usr/icu/icudt53l.dat
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/WeexCore: params_utils.cpp:270,g_jssIcuPath is /system/usr/icu/icudt53l.dat 
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: getLibJsbPath is running /data/data/com.zhaopin.ihr/cache/weex/libs/weexjsb/armeabi-v7a/libweexjsb.so
12-26 15:38:27.234 12104-12170/com.zhaopin.ihr E/weex: getLibLdPath is running /data/app/com.zhaopin.ihr-1/lib/arm:/vendor/lib:/system/lib
WeexCore: setDebugMode  2
WeexCore: script_bridge_in_multi_process.cpp:1004,ScriptBridgeInMultiProcess
12-26 15:38:27.244 12104-12170/com.zhaopin.ihr E/WeexCore: multi_process_and_so_initializer.cpp:38,MultiProcessAndSoInitializer IS IN init
12-26 15:38:27.244 12104-12170/com.zhaopin.ihr E/WeexCore: weex_js_connection.cpp:140,WeexJSConnection g_crashFileName: /data/data/com.***/app_crash/crash_dump.log
WeexCore: weex_js_connection.cpp:252,startupPie :1
weex: onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

This is all log,and then it occurs white screen.I am very confused,please help me.

**Comment by YorkShen** [comment]
Does your CPU supports arm-v7a?

For such an old CPU and mobile phone, I am afraid there is very little thing I can do.

**Comment by FightingForDevelop** [comment]
> Does your CPU supports arm-v7a?
> 
> For such an old CPU and mobile phone, I am afraid there is very little thing I can do.

My CPU supports  AArch64 Processor rev 4 (aarch64). (arm64-v8a)
ndk {
            abiFilters "armeabi-v7a", "x86"
        }
But I just supports these,even if my libs has arm64-v8a

**Comment by mattu79** [comment]
I meet the same problem with weex_sdk 0.26.0 && weex_sdk 0.28.0.
weex_sdk 0.20.3.0-beta is work fine。
