### ISSUE TITLE
[Android]When there are more than 40 images, then switch to another page, and then come back a few times to appear oomwhere weex version is 0.26.0

### ISSUE THREAD

**Issue by hponiang** [apache/incubator-weex#2944]
When there are more than 40 images, then switch to another page, and then come back a few times to appear oomwhere weex version is 0.26.0
```
--------- beginning of crash
2019-09-29 13:28:22.158 5984-5984/com.ilingdai.prod.ldapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ilingdai.prod.ldapp, PID: 5984
    java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:733)
        at com.squareup.picasso.Picasso.<init>(Picasso.java:201)
        at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)
        at com.ilingdai.prod.ldapp.extend.ImageAdapter$1.run(ImageAdapter.java:64)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-29 13:28:22.117 5984-5984/com.ilingdai.prod.ldapp W/Picasso-Dispatc: type=1400 audit(0.0:20): avc: denied { mmap_zero } for scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=memprotect permissive=0
2019-09-29 13:28:22.204 5984-5984/com.ilingdai.prod.ldapp I/Process: Sending signal. PID: 5984 SIG: 9
2019-09-29 13:28:22.127 5984-5984/com.ilingdai.prod.ldapp W/gdai.prod.ldapp: type=1400 audit(0.0:21): avc: denied { mmap_zero } for scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=memprotect permissive=0

```

**Comment by hponiang** [comment]
Because the homepage jumps to the secondary page and then returns, all the images will be loaded again。
on ImageAdapter.java
`WXSDKManager.getInstance().postOnUiThread(new Runnable() {`

**Comment by hponiang** [comment]
Now I have a temporary solution.

`	<image :autoBitmapRecycle="false" class="cover" :src="c_cover"  > </image>`

set  autoBitmapRecycle="false" and  No use image “placeholder” ，Because placeholder  and autoBitmapRecycle="ture"  creates a new thread

**Comment by YorkShen** [comment]
`ImageAdapter` is only for demo purpose, but it seems like you have already find out the solution.

Maybe you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8).

I have a busy schedule and I can't read Github issue every day, but I check mailing list every day. I am sorry if this bothers you.
