### ISSUE TITLE
[Android] 0.28.0 help!!!  update to org.apache.weex:sdk:0.28.0 ,myApp dosen't display anymore

### ISSUE THREAD

**Issue by wujianqiang6** [apache/incubator-weex#3024]
I/weex: get default settings weexjsb : 1.6.2
2019-11-19 18:17:40.938 17559-17592/company.yinu.android W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/company.myapp.android-T_fgclzaP47xVWSats4N0g==/base.apk"],nativeLibraryDirectories=[/data/app/company.yinu.android-T_fgclzaP47xVWSats4N0g==/lib/arm, /data/app/company.yinu.android-T_fgclzaP47xVWSats4N0g==/base.apk!/lib/armeabi-v7a, /system/lib]]
2019-11-19 18:17:40.939 17559-17592/company.yinu.android W/System.err:     at org.apache.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:153)
2019-11-19 18:17:40.939 17559-17592/company.yinu.android W/System.err:     at org.apache.weex.WXSDKEngine$1.run(WXSDKEngine.java:224)
2019-11-19 18:17:40.939 17559-17592/company.yinu.android W/System.err:     at org.apache.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)

**Comment by YorkShen** [comment]
Is this the same as https://github.com/apache/incubator-weex/issues/3013 ?

It also took 40s to run `nativeInitFrameworkEnv` in your phone?
