### ISSUE TITLE
[Android] renderByUrl OutOfMemoryError 是什么原因呢

### ISSUE THREAD

**Issue by hexiang1993** [apache/incubator-weex#3040]
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1572028520 byte allocation with 2479847 free bytes and 509MB until OOM, max allowed footprint 5041615, growth limit 536870912
at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:69)
at java.lang.StringBuilder.<init>(StringBuilder.java:102)
at com.taobao.weex.utils.WXFileUtils.readStreamToString(WXFileUtils.java:90)
at com.taobao.weex.utils.WXFileUtils.loadFileOrAsset(WXFileUtils.java:56)
at com.taobao.weex.WXSDKInstance.renderByUrlInternal(WXSDKInstance.java:767)
at com.taobao.weex.WXSDKInstance.renderByUrl(WXSDKInstance.java:856)

**Comment by YorkShen** [comment]
Duplicate with https://github.com/apache/incubator-weex/issues/3039
