### ISSUE TITLE
[Android][honer Mate7]Debug is all right, but Release go wrong in 0.28

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#3091]
```javascipt
12-20 17:25:38.704 3954-3954/? E/time: time1=2019年12月20日 周五
12-20 17:25:38.932 3954-3954/? E/weex: idle from create instance cache size is 0
12-20 17:25:39.487 3954-4003/? E/weex: end getBundleType type:Vue time:1
12-20 17:25:39.560 3954-4003/? E/timeline: createInstance :1576833939560
12-20 17:25:39.571 3954-4003/? E/jsEngine: script_bridge_in_multi_process.cpp:473,ScriptBridgeInMultiProcess::CreateInstance and Id is : 1
12-20 17:25:39.579 3954-4003/? E/weex: end getBundleType type:Vue time:0
12-20 17:25:39.591 3954-4003/? E/timeline: createInstance :1576833939591
12-20 17:25:39.618 3954-4003/? E/jsEngine: script_bridge_in_multi_process.cpp:473,ScriptBridgeInMultiProcess::CreateInstance and Id is : 2
12-20 17:25:39.842 3954-4003/? E/TypefaceUtil: java.lang.RuntimeException: Font asset not found Arial.ttf
12-20 17:25:39.845 3954-4003/? E/TypefaceUtil: java.lang.RuntimeException: Font asset not found ArialBold.ttf
12-20 17:25:40.045 3954-4003/? E/weex: WXComponentFactory Exception type:[image] org.apache.weex.common.WXRuntimeException: Can't find constructor of component.
        at org.apache.weex.ui.SimpleComponentHolder$ClazzComponentCreator.loadConstructor(Unknown Source)
        at org.apache.weex.ui.SimpleComponentHolder$ClazzComponentCreator.createInstance(Unknown Source)
        at org.apache.weex.ui.SimpleComponentHolder.createInstance(Unknown Source)
        at org.apache.weex.ui.component.WXComponentFactory.newInstance(Unknown Source)
        at org.apache.weex.ui.action.GraphicActionAbstractAddElement.createComponent(Unknown Source)
        at org.apache.weex.ui.action.GraphicActionAddElement.<init>(Unknown Source)
        at org.apache.weex.bridge.WXBridgeManager.callAddElement(Unknown Source)
        at org.apache.weex.bridge.WXBridge.callAddElement(Unknown Source)
        at org.apache.weex.base.SystemMessageHandler.nativeRunWork(Native Method)
        at org.apache.weex.base.SystemMessageHandler.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.os.HandlerThread.run(HandlerThread.java:61)
12-20 17:25:40.048 3954-4003/? E/weex: [WXBridgeManager] callAddElement exception: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:847)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:842)
        at org.apache.weex.ui.RenderContextImpl.registerComponent(Unknown Source)
        at org.apache.weex.ui.WXRenderManager.registerComponent(Unknown Source)
        at org.apache.weex.ui.action.GraphicActionAbstractAddElement.createComponent(Unknown Source)
        at org.apache.weex.ui.action.GraphicActionAddElement.<init>(Unknown Source)
        at org.apache.weex.bridge.WXBridgeManager.callAddElement(Unknown Source)
        at org.apache.weex.bridge.WXBridge.callAddElement(Unknown Source)
        at org.apache.weex.base.SystemMessageHandler.nativeRunWork(Native Method)
        at org.apache.weex.base.SystemMessageHandler.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.os.HandlerThread.run(HandlerThread.java:61)
12-20 17:25:40.090 3954-4003/? E/weex: WXComponentFactory Exception type:[image] org.apache.weex.common.WXRuntimeException: Can't find constructor of component.
        at org.apache.weex.ui.SimpleComponentHolder$ClazzComponentCreator.loadConstructor(Unknown Source)
        at org.apache.weex.ui.SimpleComponentHolder$ClazzComponentCreator.createInstance(Unknown Source)
        at org.apache.weex.ui.SimpleComponentHolder.createInstance(Unknown Source)
        at org.apache.weex.ui.component.WXComponentFactory.newInstance(Unknown Source)
        at org.apache.weex.ui.action.GraphicActionAbstractAddElement.createComponent(Unknown Source)
        at org.apache.weex.ui.action.GraphicActionAddElement.<init>(Unknown Source)
        at org.apache.weex.bridge.WXBridgeManager.callAddElement(Unknown Source)
        at org.apache.weex.bridge.WXBridge.callAddElement(Unknown Source)
        at org.apache.weex.base.SystemMessageHandler.nativeRunWork(Native Method)
        at org.apache.weex.base.SystemMessageHandler.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:150)
        at android.os.HandlerThread.run(HandlerThread.java:61)
12-20 17:25:40.091 3954-4003/? E/weex: [WXBridgeManager] callAddElement exception: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:847)
```

Debug is all right!
But when run App in Release Mode, error throw out like above.
Proguard-rules has set. 
BTW, the code which about android Proguard-rules on Weex-Offical-Web should change "taobao" to "apache" ?

**Comment by zsmjhtn** [comment]
extend Weex myself. And the Proguard-rules need both 
```java
-keep class org.apache.weex.** { *; }
```
```java
-keep class weex.** {*;}
```
