### ISSUE TITLE
[Android 9.0][honor Mate20] Crash on android9.0 device

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex#3096]
```javascipt
2019-12-26 10:02:00.718 23085-23114/com.xxxx E/linker: library "/system/lib/libc++_shared.so" ("/system/lib/libc++_shared.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.xxxxx-f4jNTNt3ti2sNnL5wOwljw==/lib/arm:/data/appxxxx-f4jNTNt3ti2sNnL5wOwljw==/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.xxxx"]
2019-12-26 10:02:00.722 23085-23114/com.xxxx E/weex: commitCriticalExceptionRT :WX_KEY_EXCEPTION_SDK_INITexceptionload c++_shared failed Detail Error is: dlopen failed: library "/system/lib/libc++_shared.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
2019-12-26 10:02:00.724 23085-23114/com.xxxxx E/SafeRunnable: SafeRunnable run throw expection:dlopen failed: library "/system/lib/libc++_shared.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
2019-12-26 10:02:00.729 23085-23114/com.xxxxx E/AndroidRuntime: FATAL EXCEPTION: WeexJSBridgeThread
    Process: com.ifaex_android, PID: 23085
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib/libc++_shared.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1672)
        at org.apache.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:130)
        at org.apache.weex.WXSDKEngine$1.run(WXSDKEngine.java:224)
        at org.apache.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
Weex has not support AndroidX.
Does it support Android 9.0/10.0?
Thanks

**Comment by YorkShen** [comment]
I have tested it for Android 9 (API 28), everything works fine.

If you met this problem on Android 9 with Weex 0.28, I think this is caused by the [Per-app SELinux domains](https://developer.android.com/about/versions/pie/android-9.0-changes-28) in Android 28.

You could remove libc++_shared.so provided by Weex.aar and add your own. Refer this [exmaple](https://github.com/apache/incubator-weex/blob/master/android/sdk/build.gradle#L63-L67).

**Comment by zsmjhtn** [comment]
> I have tested it for Android 9 (API 28), everything works fine.
> 
> If you met this problem on Android 9 with Weex 0.28, I think this is caused by the [Per-app SELinux domains](https://developer.android.com/about/versions/pie/android-9.0-changes-28) in Android 28.
> 
> You could remove `libc++_shared.so` provided by weex.aar and add your own. Refer this [exmaple](https://github.com/apache/incubator-weex/blob/master/android/sdk/build.gradle#L63-L67).

Solved this issue by modify **abiFilters** in Application:
```
// before  abiFilters "armeabi-v7a"
//after
 abiFilters "armeabi-v7a", 'arm64-v8a'
```
Some different between V0.18 and V0.28.
I should declare a list of abiFilters in  V0.28，rather then single “armeabi” in V0.18

**Comment by YorkShen** [comment]
Yes. `arm64-v8a` is provided accroding to Goolge Play's rule.
