### ISSUE TITLE
[Android] 0.28.0 [WXBridgeManager] invokeInitFramework  ExecuteJavaScript fail

### ISSUE THREAD

**Issue by chenyunecjtu** [apache/incubator-weex#3134]
## Describe the bug
2020-02-09 20:58:53.481 30173-30173/? I/art: Late-enabling -Xcheck:jni
2020-02-09 20:58:53.505 30173-30180/? E/art: Failed sending reply to debugger: Broken pipe
2020-02-09 20:58:53.505 30173-30180/? I/art: Debugger is no longer active
2020-02-09 20:58:53.505 30173-30180/? I/art: Starting a blocking GC Instrumentation
2020-02-09 20:58:53.742 30173-30173/? I/art: Starting a blocking GC HeapTrim
2020-02-09 20:58:53.784 30173-30195/? I/weex: get default settings weexjsb : 1.0
2020-02-09 20:58:53.806 30173-30195/? W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/data/app/com.app.videoweex-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app.videoweex-1/lib/arm, /data/app/com.app.videoweex-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at java.lang.Runtime.doLoad(Runtime.java:1072)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:987)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at java.lang.System.loadLibrary(System.java:1530)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at org.apache.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:153)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at org.apache.weex.WXSDKEngine$1.run(WXSDKEngine.java:224)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at org.apache.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:836)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at android.os.Looper.loop(Looper.java:232)
2020-02-09 20:58:53.817 30173-30195/? W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
2020-02-09 20:58:53.818 30173-30195/? E/weex: tryUseRunTimeApi ? false
2020-02-09 20:58:53.820 30173-30195/? D/SimpleComponentHolder: Generate Component:WXText
2020-02-09 20:58:53.839 30173-30195/? D/SimpleComponentHolder: Generate Component:WXDiv
2020-02-09 20:58:53.854 30173-30195/? D/SimpleComponentHolder: Generate Component:WXImage
2020-02-09 20:58:53.870 30173-30195/? D/SimpleComponentHolder: Generate Component:WXScroller
2020-02-09 20:58:53.887 30173-30195/? D/SimpleComponentHolder: Generate Component:WXSlider
2020-02-09 20:58:53.897 30173-30195/? D/SimpleComponentHolder: Generate Component:WXSliderNeighbor
2020-02-09 20:58:53.905 30173-30195/? D/SimpleComponentHolder: Generate Component:WXCell
2020-02-09 20:58:53.914 30173-30195/? D/SimpleComponentHolder: Generate Component:WXListComponent
2020-02-09 20:58:53.931 30173-30195/? D/SimpleComponentHolder: Generate Component:WXRichText
2020-02-09 20:58:53.936 30173-30195/? D/SimpleComponentHolder: Generate Component:SimpleListComponent
2020-02-09 20:58:53.948 30173-30195/? D/SimpleComponentHolder: Generate Component:WXRecyclerTemplateList
2020-02-09 20:58:53.964 30173-30195/? D/SimpleComponentHolder: Generate Component:HorizontalListComponent
2020-02-09 20:58:53.982 30173-30195/? D/SimpleComponentHolder: Generate Component:WXCell
2020-02-09 20:58:54.000 30173-30195/? D/SimpleComponentHolder: Generate Component:WXIndicator
2020-02-09 20:58:54.005 30173-30195/? D/SimpleComponentHolder: Generate Component:WXVideo
2020-02-09 20:58:54.012 30173-30195/? D/SimpleComponentHolder: Generate Component:WXInput
2020-02-09 20:58:54.020 30173-30195/? D/SimpleComponentHolder: Generate Component:Textarea
2020-02-09 20:58:54.028 30173-30195/? D/SimpleComponentHolder: Generate Component:WXSwitch
2020-02-09 20:58:54.032 30173-30195/? D/SimpleComponentHolder: Generate Component:WXA
2020-02-09 20:58:54.043 30173-30195/? D/SimpleComponentHolder: Generate Component:WXEmbed
2020-02-09 20:58:54.051 30173-30195/? D/SimpleComponentHolder: Generate Component:WXWeb
2020-02-09 20:58:54.057 30173-30195/? D/SimpleComponentHolder: Generate Component:WXRefresh
2020-02-09 20:58:54.064 30173-30195/? D/SimpleComponentHolder: Generate Component:WXLoading
2020-02-09 20:58:54.070 30173-30195/? D/SimpleComponentHolder: Generate Component:WXLoadingIndicator
2020-02-09 20:58:54.074 30173-30195/? D/SimpleComponentHolder: Generate Component:WXHeader
2020-02-09 20:58:54.081 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXModalUIModule
2020-02-09 20:58:54.084 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.085 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXInstanceWrap
2020-02-09 20:58:54.087 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.088 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXAnimationModule
2020-02-09 20:58:54.090 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.090 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXWebViewModule
2020-02-09 20:58:54.094 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.094 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXNavigatorModule
2020-02-09 20:58:54.099 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.099 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXStreamModule
2020-02-09 20:58:54.101 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.102 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXTimerModule
2020-02-09 20:58:54.105 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.105 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXStorageModule
2020-02-09 20:58:54.109 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.110 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXClipboardModule
2020-02-09 20:58:54.112 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.112 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXGlobalEventModule
2020-02-09 20:58:54.114 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.115 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXPickersModule
2020-02-09 20:58:54.124 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.125 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXMetaModule
2020-02-09 20:58:54.127 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.128 30173-30195/? D/TypeModuleFactory: extractMethodNames:WebSocketModule
2020-02-09 20:58:54.138 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.138 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXLocaleModule
2020-02-09 20:58:54.147 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.148 30173-30195/? D/TypeModuleFactory: extractMethodNames:WXDeviceInfoModule
2020-02-09 20:58:54.150 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.151 30173-30195/? D/TypeModuleFactory: extractMethodNames:ConsoleLogModule
2020-02-09 20:58:54.164 30173-30195/? D/weex: [WXinvokeRegisterModulesBridgeManager] invokeRegisterModules: framework.js uninitialized.
2020-02-09 20:58:54.196 30173-30195/? W/weex: app AvailMemory ---->>>630
2020-02-09 20:58:54.196 30173-30195/? D/weex: weex JS framework from assets
2020-02-09 20:58:54.204 30173-30195/? D/weex: [WXBridgeManager] initFrameworkEnv crashFile:/data/user/0/com.app.videoweex/cache pieSupport:true
2020-02-09 20:58:54.217 30173-30195/? E/WXParams: setCrashFilePath: /data/user/0/com.app.videoweex/app_crash
2020-02-09 20:58:54.218 30173-30195/? E/weex: weexjss's Path is/data/app/com.app.videoweex-1/lib/arm/libweexjss.so
2020-02-09 20:58:54.218 30173-30195/? D/weex: test-> findLibJssRealPath /data/app/com.app.videoweex-1/lib/arm/libweexjss.so
2020-02-09 20:58:54.226 30173-30195/? D/weex: getLibLdPath is /data/app/com.app.videoweex-1/lib/arm:/data/app/com.app.videoweex-1/base.apk!/lib/armeabi-v7a
2020-02-09 20:58:54.306 30173-30173/? V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@1ae0093[]
2020-02-09 20:58:54.339 30173-30173/? V/ViewRootImpl: enableLogLight: enable = false
2020-02-09 20:58:54.342 30173-30173/? D/WindowClient: Add to mViews: DecorView@1ae0093[LanucherActivity], this = android.view.WindowManagerGlobal@f5d9d56
2020-02-09 20:58:54.352 30173-30173/? D/OpenGLRenderer: Dumper init 4 threads <0xe0d64ec0>
2020-02-09 20:58:54.352 30173-30173/? D/OpenGLRenderer: <com.app.videoweex> is running.
2020-02-09 20:58:54.357 30173-30234/? D/OpenGLRenderer: CanvasContext() 0xce01aa00
2020-02-09 20:58:54.395 30173-30173/? D/ViewRootImpl[LanucherActivity]: hardware acceleration is enabled, this = ViewRoot{75061d7 com.app.videoweex/com.app.videoweex.LanucherActivity,ident = 0}
2020-02-09 20:58:54.413 30173-30173/? V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{75061d7 com.app.videoweex/com.app.videoweex.LanucherActivity,ident = 0}, this = DecorView@1ae0093[LanucherActivity]
2020-02-09 20:58:54.443 30173-30173/? V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = ViewRoot{75061d7 com.app.videoweex/com.app.videoweex.LanucherActivity,ident = 0}, this = DecorView@1ae0093[LanucherActivity]
2020-02-09 20:58:54.485 30173-30173/? E/cody: path:/test.js
2020-02-09 20:58:54.485 30173-30173/? E/cody: host:
2020-02-09 20:58:54.495 30173-30173/? V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@c8d5f30[]
2020-02-09 20:58:54.497 30173-30173/com.app.videoweex V/ViewRootImpl: enableLogLight: enable = false
2020-02-09 20:58:54.501 30173-30173/com.app.videoweex D/WindowClient: Add to mViews: DecorView@c8d5f30[MainActivity], this = android.view.WindowManagerGlobal@f5d9d56
2020-02-09 20:58:54.505 30173-30234/com.app.videoweex D/OpenGLRenderer: CanvasContext() 0xce066440
2020-02-09 20:58:54.506 30173-30173/com.app.videoweex D/ViewRootImpl[MainActivity]: hardware acceleration is enabled, this = ViewRoot{8b4cdf2 com.app.videoweex/com.app.videoweex.MainActivity,ident = 1}
2020-02-09 20:58:54.512 30173-30173/com.app.videoweex V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{8b4cdf2 com.app.videoweex/com.app.videoweex.MainActivity,ident = 1}, this = DecorView@c8d5f30[MainActivity]
2020-02-09 20:58:54.516 30173-30173/com.app.videoweex I/Choreographer: Skipped 6 frames!  The application may be doing too much work on its main thread.
2020-02-09 20:58:54.581 30173-30173/com.app.videoweex D/Surface: Surface::allocateBuffers(this=0xce065000)
2020-02-09 20:58:54.581 30173-30234/com.app.videoweex D/OpenGLRenderer: CanvasContext() 0xce066440 initialize window=0xce065000, title=com.app.videoweex/com.app.videoweex.MainActivity
2020-02-09 20:58:54.607 30173-30234/com.app.videoweex I/OpenGLRenderer: Initialized EGL, version 1.4
2020-02-09 20:58:54.607 30173-30234/com.app.videoweex D/OpenGLRenderer: Swap behavior 1
2020-02-09 20:58:54.607 30173-30234/com.app.videoweex D/libEGL: [FRR] clean FRR20 bit (2)
2020-02-09 20:58:54.607 30173-30234/com.app.videoweex D/libEGL: [GIFT] clean GIFT bit (0)
2020-02-09 20:58:54.610 30173-30234/com.app.videoweex D/OpenGLRenderer: Created EGL context (0xdd67dfc0)
2020-02-09 20:58:54.612 30173-30234/com.app.videoweex D/OpenGLRenderer: ProgramCache.init: enable enhancement 1
2020-02-09 20:58:54.612 30173-30234/com.app.videoweex I/OpenGLRenderer: Get disable program binary service property (0)
2020-02-09 20:58:54.612 30173-30234/com.app.videoweex I/OpenGLRenderer: Initializing program atlas...
2020-02-09 20:58:54.614 30173-30234/com.app.videoweex I/ProgramBinary/Service: ProgramBinaryService client side disable debugging.
2020-02-09 20:58:54.614 30173-30234/com.app.videoweex I/ProgramBinary/Service: ProgramBinaryService client side disable binary content debugging.
2020-02-09 20:58:54.614 30173-30234/com.app.videoweex D/ProgramBinary/Service: BpProgramBinaryService.getReady
2020-02-09 20:58:54.614 30173-30234/com.app.videoweex D/ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryData
2020-02-09 20:58:54.615 30173-30234/com.app.videoweex I/OpenGLRenderer: Program binary detail: Binary length is 454736, program map length is 124.
2020-02-09 20:58:54.616 30173-30234/com.app.videoweex I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 69, and path is /dev/ashmem.
2020-02-09 20:58:54.616 30173-30234/com.app.videoweex I/OpenGLRenderer: No need to use file discriptor anymore, close fd(69).
2020-02-09 20:58:54.616 30173-30234/com.app.videoweex D/OpenGLRenderer: Initializing program cache from 0x0, size = -1
2020-02-09 20:58:54.618 30173-30234/com.app.videoweex W/libEGL: [ANDROID_RECORDABLE] format: 1
2020-02-09 20:58:54.621 30173-30234/com.app.videoweex D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
2020-02-09 20:58:54.631 30173-30195/com.app.videoweex E/weex: findLibJscRealPath /data/user/0/com.app.videoweex/cache/libjsc.so
2020-02-09 20:58:54.632 30173-30195/com.app.videoweex E/weex: enableAlarmSignal:true
2020-02-09 20:58:54.632 30173-30195/com.app.videoweex E/weex: getUseSingleProcess is running false
2020-02-09 20:58:54.633 30173-30195/com.app.videoweex E/WeexCore: params_utils.cpp:197,g_use_single_process is false 
2020-02-09 20:58:54.633 30173-30195/com.app.videoweex E/weex: getLibJscPath is running /data/user/0/com.app.videoweex/cache
2020-02-09 20:58:54.633 30173-30195/com.app.videoweex E/WeexCore: params_utils.cpp:232,g_jscSoPath is /data/user/0/com.app.videoweex/cache 
2020-02-09 20:58:54.633 30173-30195/com.app.videoweex E/weex: getLibJssPath is running /data/app/com.app.videoweex-1/lib/arm/libweexjss.so
2020-02-09 20:58:54.634 30173-30195/com.app.videoweex E/WeexCore: params_utils.cpp:245,g_jssSoPath is /data/app/com.app.videoweex-1/lib/arm/libweexjss.so 
2020-02-09 20:58:54.634 30173-30195/com.app.videoweex E/WXParams: getCrashFilePath:/data/user/0/com.app.videoweex/app_crash
2020-02-09 20:58:54.634 30173-30195/com.app.videoweex E/WeexCore: params_utils.cpp:257,g_crashFilePath is /data/user/0/com.app.videoweex/app_crash 
2020-02-09 20:58:54.634 30173-30195/com.app.videoweex E/weex: getLibIcuPath is running /system/usr/icu/icudt56l.dat
2020-02-09 20:58:54.634 30173-30195/com.app.videoweex E/WeexCore: params_utils.cpp:270,g_jssIcuPath is /system/usr/icu/icudt56l.dat 
2020-02-09 20:58:54.634 30173-30195/com.app.videoweex E/weex: getLibJsbPath is running /data/data/com.app.videoweex/cache/weex/libs/weexjsb/armeabi-v7a/libweexjsb.so
2020-02-09 20:58:54.635 30173-30195/com.app.videoweex E/weex: getLibLdPath is running /data/app/com.app.videoweex-1/lib/arm:/data/app/com.app.videoweex-1/base.apk!/lib/armeabi-v7a
2020-02-09 20:58:54.640 30173-30195/com.app.videoweex E/WeexCore: setDebugMode  2 
2020-02-09 20:58:54.640 30173-30195/com.app.videoweex D/WeexCore: script_bridge_in_multi_process.cpp:1004,ScriptBridgeInMultiProcess
2020-02-09 20:58:54.641 30173-30195/com.app.videoweex E/WeexCore: multi_process_and_so_initializer.cpp:38,MultiProcessAndSoInitializer IS IN init
2020-02-09 20:58:54.641 30173-30195/com.app.videoweex E/WeexCore: weex_js_connection.cpp:140,WeexJSConnection g_crashFileName: /data/user/0/com.app.videoweex/app_crash/crash_dump.log
2020-02-09 20:58:54.641 30173-30195/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:46,id: 0
2020-02-09 20:58:54.642 30173-30195/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:106,lock: 0
2020-02-09 20:58:54.643 30173-30173/com.app.videoweex I/Choreographer: Skipped 6 frames!  The application may be doing too much work on its main thread.
2020-02-09 20:58:54.643 30173-30276/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:46,id: 0
2020-02-09 20:58:54.644 30173-30276/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:106,lock: 0
2020-02-09 20:58:54.644 30173-30195/com.app.videoweex E/WeexCore: weex_js_connection.cpp:252,startupPie :1
2020-02-09 20:58:54.673 30173-30234/com.app.videoweex D/OpenGLRenderer: CacheTexture 2 upload: x, y, width height = 0, 0, 160, 104
2020-02-09 20:58:54.685 30173-30234/com.app.videoweex D/OpenGLRenderer: ProgramCache.generateProgram: 0
2020-02-09 20:58:54.687 30173-30234/com.app.videoweex D/OpenGLRenderer: ProgramCache.generateProgram: 240518168576
2020-02-09 20:58:54.689 30173-30234/com.app.videoweex D/OpenGLRenderer: ProgramCache.generateProgram: 68724719680
2020-02-09 20:58:54.691 30173-30234/com.app.videoweex D/OpenGLRenderer: ProgramCache.generateProgram: 34359738371
2020-02-09 20:58:54.703 30173-30234/com.app.videoweex I/PerfService: PerfServiceNative api init
2020-02-09 20:58:54.710 30173-30173/com.app.videoweex V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
2020-02-09 20:58:54.715 30173-30173/com.app.videoweex I/Choreographer: Skipped 3 frames!  The application may be doing too much work on its main thread.
2020-02-09 20:59:26.929 30173-30195/com.app.videoweex E/WeexCore: weex_js_connection.cpp:288,WeexJSConnection catch: spinWaitPeer timeout
2020-02-09 20:59:26.929 30173-30276/com.app.videoweex E/WeexCore: weex_js_connection.cpp:183,IPCException server died spinWaitPeer timeout
2020-02-09 20:59:26.929 30173-30195/com.app.videoweex E/WeexCore: multi_process_and_so_initializer.cpp:47,JSFramwork init start sender is null
2020-02-09 20:59:26.929 30173-30195/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:81,unlock: 0
2020-02-09 20:59:26.931 30173-30195/com.app.videoweex E/WeexCore: weex_js_connection.cpp:140,WeexJSConnection g_crashFileName: /data/user/0/com.app.videoweex/app_crash/crash_dump.log
2020-02-09 20:59:26.931 30173-30195/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:46,id: 0
2020-02-09 20:59:26.931 30173-30195/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:106,lock: 0
2020-02-09 20:59:26.932 30173-30462/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:46,id: 0
2020-02-09 20:59:26.933 30173-30462/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:106,lock: 0
2020-02-09 20:59:26.933 30173-30195/com.app.videoweex E/WeexCore: weex_js_connection.cpp:252,startupPie :1
2020-02-09 20:59:59.911 30173-30462/com.app.videoweex E/WeexCore: weex_js_connection.cpp:183,IPCException server died spinWaitPeer timeout
2020-02-09 20:59:59.911 30173-30195/com.app.videoweex E/WeexCore: weex_js_connection.cpp:288,WeexJSConnection catch: spinWaitPeer timeout
2020-02-09 20:59:59.911 30173-30195/com.app.videoweex E/WeexCore: multi_process_and_so_initializer.cpp:47,JSFramwork init start sender is null
2020-02-09 20:59:59.911 30173-30195/com.app.videoweex D/WeexCore: IPCFutexPageQueue.cpp:81,unlock: 0
2020-02-09 20:59:59.914 30173-30195/com.app.videoweex E/WeexCore: script_side_in_multi_process.cpp:43,InitFramework sender is null
2020-02-09 20:59:59.917 30173-30195/com.app.videoweex E/weex: [WXBridgeManager] invokeInitFramework  ExecuteJavaScript fail

## Expected behavior
初始化失败，不能渲染页面，如果使用 com.taobao.android:weex_sdk:0.20.3.0-beta 就没有问题，正常加载页面

**Comment by bcshmily** [comment]
一样的问题
E/WeexCore: weex_js_connection.cpp:183,IPCException server died spinWaitPeer timeout
E/WeexCore: script_side_in_multi_process.cpp:43,InitFramework sender is null
E/weex: [WXBridgeManager] invokeInitFramework  ExecuteJavaScript fail

**Comment by hefuweill** [comment]
一样的问题，浪费了很多时间。

**Comment by wuxq** [comment]
这个问题解决了吗
