### ISSUE TITLE
使用vue+weex使用出现，Layer overflow limit error

### ISSUE THREAD

**Issue by SmallJohnSir** [apache/incubator-weex#3157]
## Describe the bug

/Layer overflow limit error: java.lang.StackOverflowError
## To Reproduce

使用vue+weex的时候出现，点击时候部分渲染完成，部分没渲染完成，
想知道报这个错误的原因，是因为div太多层吗
Layer overflow limit error: java.lang.StackOverflowError
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:160)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.calLayerDeep(WXFrameLayout.java:161)
        at com.taobao.weex.ui.view.WXFrameLayout.reportLayerOverFlowError(WXFrameLayout.java:133)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDraw(WXFrameLayout.java:124)
        at android.view.View.draw(View.java:14594)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13488)
        at android.view.View.getDisplayList(View.java:13530)
        at android.view.View.draw(View.java:14308)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDrawInterval(WXFrameLayout.java:154)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDraw(WXFrameLayout.java:116)
        at android.view.View.draw(View.java:14594)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13488)
        at android.view.View.getDisplayList(View.java:13530)
        at android.view.View.draw(View.java:14308)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDrawInterval(WXFrameLayout.java:154)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDraw(WXFrameLayout.java:116)
        at android.view.View.draw(View.java:14594)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13488)
        at android.view.View.getDisplayList(View.java:13530)
        at android.view.View.draw(View.java:14308)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDrawInterval(WXFrameLayout.java:154)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDraw(WXFrameLayout.java:116)
        at android.view.View.draw(View.java:14594)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13488)
        at android.view.View.getDisplayList(View.java:13530)
        at android.view.View.draw(View.java:14308)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDrawInterval(WXFrameLayout.java:154)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDraw(WXFrameLayout.java:116)
        at android.view.View.draw(View.java:14594)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.view.View.getDisplayList(View.java:13488)
        at android.view.View.getDisplayList(View.java:13530)
        at android.view.View.draw(View.java:14308)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDrawInterval(WXFrameLayout.java:154)
        at com.taobao.weex.ui.view.WXFrameLayout.dispatchDraw(WXFrameLayout.java:116)
        at android.view.View.draw(View.java:14594)
    	at
## Environment

Device: [android]
Version [api 19]
Build from source [yes]

**Comment by cnryb** [comment]
发现层级压测的demo，你可以试一下。 https://hanks10100.github.io/weex-vue-examples/#others/layer-benchmark
