### ISSUE TITLE
android 报错加载js页面白屏

### ISSUE THREAD

**Issue by kxliu1990** [apache/incubator-weex#3207]
System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[
System.err:     at org.apache.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:153)
System.err:     at org.apache.weex.WXSDKEngine$1.run(WXSDKEngine.java:224)
System.err:     at org.apache.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)

**Comment by cnryb** [comment]
请明确一下问题复现步骤。

**Comment by limingwei** [comment]
+1

**Comment by SkunkBoy** [comment]
请问这个问题解决了吗？
这个步骤就是参照官网配置，运行demo
之后就成白屏了。
System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge"

**Comment by SkunkBoy** [comment]
我的解决方案：
classpath "com.android.tools.build:gradle:3.5.3"
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
