### ISSUE TITLE
 0.28#Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge

### ISSUE THREAD

**Issue by SkunkBoy** [apache/incubator-weex#3327]
W/System.err: java.lang.ClassNotFoundException: Didn't find class "com.taobao.windmill.bundle.bridge.WeexBridge" on path: DexPathList[[zip file "/data/app/xxxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/-1/lib/arm64, /data/app//base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 at java.lang.Runtime.nativeLoad(Native Method)
 at java.lang.Runtime.doLoad(Runtime.java:435)
 at java.lang.Runtime.loadLibrary(Runtime.java:370)
 at java.lang.System.loadLibrary(System.java:1076)
 at org.apache.weex.utils.WXSoInstallMgrSdk.initSo(WXSoInstallMgrSdk.java:153)
 at org.apache.weex.WXSDKEngine$1.run(WXSDKEngine.java:224)
 at org.apache.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)
 at android.os.Handler.handleCallback(Handler.java:742)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:157)
 at android.os.HandlerThread.run(HandlerThread.java:61)
Suppressed: java.lang.ClassNotFoundException: com.taobao.windmill.bundle.bridge.WeexBridge
 at java.lang.Class.classForName(Native Method)
 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 12 more
aused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
 E/weex: tryUseRunTimeApi ? false

**Comment by SkunkBoy** [comment]
解决办法：
classpath "com.android.tools.build:gradle:3.5.3"
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by jiyarong** [comment]
> classpath "com.android.tools.build:gradle:3.5.3"
> distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip

哥，这个在哪里设置啊，急，谢谢
